### ISSUE TITLE
Document valid key names

### ISSUE THREAD

**Issue by noctuid** [ReimuNotMoe/ydotool#10]
Key naming is not compatible with xdotool (e.g. `ydotool key space` and `ydotool key return` don't work but `ydotool key " "` and `ydotool key enter` do). It would be nice if there was a link in the readme to somewhere that listed valid keys.

**Comment by ReimuNotMoe** [comment]
At this time, you can have a look at `/usr/include/linux/input-event-codes.h`.

I plan to make some aliases to these key names that is compatible with xdotool ones.

**Comment by roipoussiere** [comment]
> I plan to make some aliases to these key names that is compatible with xdotool ones.

Maybe it's the same keycodes, but they should at least be compatible with [wev](https://git.sr.ht/~sircmpwn/wev) (xev alternative for Wayland), in this way users could test inputs before trying commands.

**Comment by ClassicOldSong** [comment]
@roipoussiere is `wev` fully compatible with `xev`?

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76

**Comment by MoltenMonster** [comment]
@ReimuNotMoe I'm on NixOS and am unsure how to access `/usr/include/linux/input-event-codes.h`, and it doesn't seem like I should be accessing directories like that anyway.

**Comment by l0b0** [comment]
I found a bunch in `/nix/store/*linux-headers*/include/linux/input-event-codes.h`
