### ISSUE TITLE
Don't require an internet connection for building

### ISSUE THREAD

**Issue by raingloom** [ReimuNotMoe/ydotool#104]
Hi! I'm trying to package ydotool on Guix! I'm running into issues due to the following:

> All dependencies will be configured by CPM automatically to save you from building & installing them manually. So an Internet connection is required.

This might explain why when I looked at how NixOS packages it, I found out they only have an older version.

So I'm putting this package to the side for now, because I am not going to run a build with internet access (no sane person should do that, it completely undermines trust in packages) and I don't want to write my own CMakeLists.txt if I can avoid it.

ps.: I really like that it's under AGPL. Although hosting it on GitHub undermines that a bit. Still, good license choice.

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
