### ISSUE TITLE
How to emulate less common key buttons?

### ISSUE THREAD

**Issue by jplatte** [ReimuNotMoe/ydotool#107]
I've tried emulating the back and forwards button available on some mice using:

* `ydotool click back` / `ydotool click forward`
* `ydotool key btn_back` / `ydotool key btn_forward` and the same with `-` instead of `_` / all-uppercase
  (since `/usr/include/linux/input-event-codes.h` referened in the readme has definitions for `BTN_BACK` and `BTN_FORWARD`)

None of these seem to work.

Luckily `alt+left` and `alt+right` work as an alternative in all of the application I've tried, but it would be nice if emulating less common mouse buttons was supported too.

**Comment by Frenzie** [comment]
Indeed, I see https://github.com/ReimuNotMoe/ydotool/pull/71 but I tried the same options and they don't seem to work.

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
