### ISSUE TITLE
Manpages attempting to install to `/man1`

### ISSUE THREAD

**Issue by saulrh** [ReimuNotMoe/ydotool#109]
`CMAKE_INSTALL_MANPATH` comes out empty for me, so [the install statement for manpages](https://github.com/ReimuNotMoe/ydotool/blob/b1d041f52f7bac364d6539b1251d29c3b77c0f37/manpage/CMakeLists.txt#L5) attempts to blindly install the manpages to `/man1`. Not sure what the root cause is; could be misconfiguration on my end or it could be something up with your use of [`GNUInstallDirs`](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html).

**Comment by saulrh** [comment]
Workaround: editing the `CMakeLists.txt` to manually insert a correct path.

**Comment by maxice8** [comment]
This should be fixed by #114 which adds an include to `GNUInstallDirs`, filling `CMAKE_INSTALL_MANDIR` with a sane default
