### ISSUE TITLE
systemd service unit assumes `ydotoold` is installed at `/usr/bin/ydotoold`

### ISSUE THREAD

**Issue by saulrh** [ReimuNotMoe/ydotool#110]
Offending line: https://github.com/ReimuNotMoe/ydotool/blob/b1d041f52f7bac364d6539b1251d29c3b77c0f37/Daemon/ydotool.service#L7

This could be fixed by using `configure_file` with a `ydotool.service.in` to substitute the value of `CMAKE_INSTALL_BINDIR` in to direct the systemd unit to the right spot.

Workaround: Manually edit the systemd unit file before installation.

**Comment by maxice8** [comment]
Fixed by #114 @ReimuNotMoe
