### ISSUE TITLE
mousemove --absolute works only sometimes

### ISSUE THREAD

**Issue by gapf2010** [ReimuNotMoe/ydotool#111]
I'm running Fedora 34, and using something like "ydotool mousemove --absolute 10 10" works only sometimes. First time I run it, it will do nothing, second time (same command) it will move the mouse to 0,0 (no matter the x and y values). Third time, it will work correctly. If I don't use the --absolute option (relative movement) it seems to work reliably.

**Comment by Tehgg** [comment]
Apparently, if one duplicate the line `uInputContext->send_pos_relative({-INT32_MAX, -INT32_MAX});` in the function `MouseMove::run` of `Tools/MouseMove/MouseMove.cpp`, it works. Strange.

**Comment by ReimuNotMoe** [comment]
It seems that you're using an older release of ydotool. Please build the latest version and see if the problem persists. Thanks.
