### ISSUE TITLE
Does not work with latest version of IODash

### ISSUE THREAD

**Issue by bhepple** [ReimuNotMoe/ydotool#116]
Not a big deal but, I have tried the latest tag of IODash v0.1.8 and it compiles. But ydotool now fails silently!!

```
$ sudo ydotool type -- foo
ydotool: notice: Using ydotoold backend
$
```

With the older IODash v0.1.0, I get the expected result, viz:

```
$ sudo ydotool type -- foo
ydotool: notice: Using ydotoold backend
foo$ foo
```

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
