### ISSUE TITLE
ydotool implicit mousemove misinterprets negative symbol (-) as parameter

### ISSUE THREAD

**Issue by adeliktas** [ReimuNotMoe/ydotool#119]
As in the Readme implicit mousemove Example:
ydotool mousemove -100 100
or ydotool mousemove "-100" "100"

ydotool: notice: Using ydotoold backend
Ooooops! Option ‘1’ does not exist

execve("/usr/local/bin/ydotool", ["ydotool", "mousemove", "-100", "100"], 0x7ffdf85ec6b8 /* 40 vars */) = 0

But it does work with specifying it explicitly
ydotool mousemove -x -100 -y 100

So a minor bug fix is required.

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
