### ISSUE TITLE
AUR build broken after redesign

### ISSUE THREAD

**Issue by norcalli** [ReimuNotMoe/ydotool#12]
```cpp
[ 70%] Building CXX object CMakeFiles/key.dir/Tools/Key/Key.cpp.o 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Daemon/ydotoold.cpp: In function ‘int client_handler(int)’: 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Daemon/ydotoold.cpp:31:2: error: ‘uInputRawData’ was not declared in this scope 
  uInputRawData buf{0}; 
  ^~~~~~~~~~~~~ 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Daemon/ydotoold.cpp:34:22: error: ‘buf’ was not declared in this scope 
   int rc = recv(fd, &buf, sizeof(buf), MSG_WAITALL); 
                      ^~~ 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.cpp: In function ‘int socket_callback(uint16_t, uint16_t, int32_t, void*)’: 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.cpp:75:2: error: ‘uInputRawData’ was not declared in this scope 
  uInputRawData buf{0}; 
  ^~~~~~~~~~~~~ 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.cpp:76:2: error: ‘buf’ was not declared in this scope 
  buf.type = type; 
  ^~~ 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.cpp:83:1: warning: no return statement in function returning non-void [-Wreturn-type] 
 } 
 ^ 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.cpp: In function ‘int main(int, const char**)’: 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.cpp:122:59: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast] 
   instance->uInputContext->Init(&socket_callback, (void *)fd_client); 
                                                           ^~~~~~~~~ 
/home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.cpp:122:68: error: no matching function for call to ‘uInputPlus::uInput::Init(int (*)(uint16_t, uint16_t, int32_t, void*), void*)’ 
   instance->uInputContext->Init(&socket_callback, (void *)fd_client); 
                                                                    ^ 
In file included from /home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/../CommonIncludes.hpp:36, 
                 from /home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.hpp:17, 
                 from /home/ashkan/.cache/yay/ydotool-git/src/ydotool/Client/ydotool.cpp:13: 
/usr/include/uInputPlus/uInput.hpp:44:7: note: candidate: ‘void uInputPlus::uInput::Init(const uInputPlus::uInputSetup&)’ 
  void Init(const uInputSetup &setup); 
       ^~~~ 
/usr/include/uInputPlus/uInput.hpp:44:7: note:   candidate expects 1 argument, 2 provided 
make[2]: *** [CMakeFiles/ydotoold.dir/build.make:63: CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o] Error 1 
make[1]: *** [CMakeFiles/Makefile2:295: CMakeFiles/ydotoold.dir/all] Error 2 
make[1]: *** Waiting for unfinished jobs.... 
make[2]: *** [CMakeFiles/ydotool_client.dir/build.make:63: CMakeFiles/ydotool_client.dir/Client/ydotool.cpp.o] Error 1 
make[1]: *** [CMakeFiles/Makefile2:221: CMakeFiles/ydotool_client.dir/all] Error 2 
[ 75%] Linking CXX shared library libclick.so 
[ 80%] Linking CXX shared library libmousemove.so 
[ 85%] Linking CXX shared library libtype.so 
[ 85%] Built target click 
[ 85%] Built target type 
[ 85%] Built target mousemove 
[ 90%] Linking CXX shared library libkey.so 
[ 90%] Built target key 
make: *** [Makefile:152: all] Error 2 
==> ERROR: A failure occurred in build(). 
    Aborting... 
Error making: ydotool-git 
```

**Comment by Xieyt** [comment]
Same when building on ubuntu 19.04

water@water-pc:~/ydotool/build$ sudo cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/water/ydotool/build
water@water-pc:~/ydotool/build$ sudo make -j `nproc`
Scanning dependencies of target ydotool_library
Scanning dependencies of target ydotool_library_static
[ 15%] Building CXX object CMakeFiles/ydotool_library.dir/Library/Instance.cpp.o
[ 15%] Building CXX object CMakeFiles/ydotool_library.dir/Library/libydotool.cpp.o
[ 15%] Building CXX object CMakeFiles/ydotool_library.dir/Library/Tool.cpp.o
[ 20%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Instance.cpp.o
[ 25%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/libydotool.cpp.o
[ 30%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Tool.cpp.o
[ 35%] Linking CXX static library libydotool.a
[ 35%] Built target ydotool_library_static
[ 40%] Linking CXX shared library libydotool.so
[ 40%] Built target ydotool_library
Scanning dependencies of target ydotoold
Scanning dependencies of target ydotool_client
Scanning dependencies of target key
Scanning dependencies of target click
Scanning dependencies of target type
Scanning dependencies of target mousemove
[ 50%] Building CXX object CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o
[ 50%] Building CXX object CMakeFiles/ydotool_client.dir/Client/ydotool.cpp.o
[ 60%] Building CXX object CMakeFiles/mousemove.dir/Tools/MouseMove/MouseMove.cpp.o
[ 60%] Building CXX object CMakeFiles/key.dir/Tools/Key/Key.cpp.o
[ 65%] Building CXX object CMakeFiles/click.dir/Tools/Click/Click.cpp.o
[ 70%] Building CXX object CMakeFiles/type.dir/Tools/Type/Type.cpp.o
/home/water/ydotool/Daemon/ydotoold.cpp: In function ‘int client_handler(int)’:
/home/water/ydotool/Daemon/ydotoold.cpp:31:2: error: ‘uInputRawData’ was not declared in this scope
  uInputRawData buf{0};
  ^~~~~~~~~~~~~
/home/water/ydotool/Daemon/ydotoold.cpp:34:22: error: ‘buf’ was not declared in this scope
   int rc = recv(fd, &buf, sizeof(buf), MSG_WAITALL);
                      ^~~
/home/water/ydotool/Client/ydotool.cpp: In function ‘int socket_callback(uint16_t, uint16_t, int32_t, void*)’:
/home/water/ydotool/Client/ydotool.cpp:75:2: error: ‘uInputRawData’ was not declared in this scope
  uInputRawData buf{0};
  ^~~~~~~~~~~~~
/home/water/ydotool/Client/ydotool.cpp:76:2: error: ‘buf’ was not declared in this scope
  buf.type = type;
  ^~~
/home/water/ydotool/Client/ydotool.cpp:83:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
/home/water/ydotool/Client/ydotool.cpp: In function ‘int main(int, const char**)’:
/home/water/ydotool/Client/ydotool.cpp:122:59: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   instance->uInputContext->Init(&socket_callback, (void *)fd_client);
                                                           ^~~~~~~~~
/home/water/ydotool/Client/ydotool.cpp:122:68: error: no matching function for call to ‘uInputPlus::uInput::Init(int (*)(uint16_t, uint16_t, int32_t, void*), void*)’
   instance->uInputContext->Init(&socket_callback, (void *)fd_client);
                                                                    ^
In file included from /home/water/ydotool/Client/../CommonIncludes.hpp:36,
                 from /home/water/ydotool/Client/ydotool.hpp:17,
                 from /home/water/ydotool/Client/ydotool.cpp:13:
/usr/local/include/uInputPlus/uInput.hpp:44:7: note: candidate: ‘void uInputPlus::uInput::Init(const uInputPlus::uInputSetup&)’
  void Init(const uInputSetup &setup);
       ^~~~
/usr/local/include/uInputPlus/uInput.hpp:44:7: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/ydotoold.dir/build.make:63: CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/ydotoold.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/ydotool_client.dir/build.make:63: CMakeFiles/ydotool_client.dir/Client/ydotool.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:332: CMakeFiles/ydotool_client.dir/all] Error 2
[ 75%] Linking CXX shared library libmousemove.so
[ 80%] Linking CXX shared library libclick.so
[ 85%] Linking CXX shared library libtype.so
[ 85%] Built target mousemove
[ 85%] Built target click
[ 85%] Built target type
[ 90%] Linking CXX shared library libkey.so
[ 90%] Built target key
make: *** [Makefile:152: all] Error 2

**Comment by ReimuNotMoe** [comment]
Sorry, I forgot to commit changes to [libuInputPlus](https://github.com/YukiWorkshop/libuInputPlus).

Please pull and try recompile.

**Comment by Xieyt** [comment]
After that this issue came


$ make -j `nproc`
Scanning dependencies of target ydotool_library
Scanning dependencies of target ydotool_library_static
[  5%] Building CXX object CMakeFiles/ydotool_library.dir/Library/Instance.cpp.o
[ 10%] Building CXX object CMakeFiles/ydotool_library.dir/Library/Tool.cpp.o
[ 15%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Tool.cpp.o
[ 20%] Building CXX object CMakeFiles/ydotool_library.dir/Library/libydotool.cpp.o
[ 25%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/libydotool.cpp.o
[ 30%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Instance.cpp.o
[ 35%] Linking CXX shared library libydotool.so
[ 40%] Linking CXX static library libydotool.a
[ 40%] Built target ydotool_library
[ 40%] Built target ydotool_library_static
Scanning dependencies of target mousemove
Scanning dependencies of target type
Scanning dependencies of target key
Scanning dependencies of target ydotoold
Scanning dependencies of target click
Scanning dependencies of target ydotool_client
[ 45%] Building CXX object CMakeFiles/type.dir/Tools/Type/Type.cpp.o
[ 50%] Building CXX object CMakeFiles/mousemove.dir/Tools/MouseMove/MouseMove.cpp.o
[ 55%] Building CXX object CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o
[ 60%] Building CXX object CMakeFiles/click.dir/Tools/Click/Click.cpp.o
[ 65%] Building CXX object CMakeFiles/key.dir/Tools/Key/Key.cpp.o
[ 70%] Building CXX object CMakeFiles/ydotool_client.dir/Client/ydotool.cpp.o
/home/water/ydotool/Client/ydotool.cpp: In function ‘int socket_callback(uint16_t, uint16_t, int32_t, void*)’:
/home/water/ydotool/Client/ydotool.cpp:83:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
/home/water/ydotool/Client/ydotool.cpp: In function ‘int main(int, const char**)’:
/home/water/ydotool/Client/ydotool.cpp:122:59: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   instance->uInputContext->Init(&socket_callback, (void *)fd_client);
                                                           ^~~~~~~~~
[ 75%] Linking CXX executable ydotoold
[ 80%] Linking CXX executable ydotool
[ 80%] Built target ydotoold
[ 80%] Built target ydotool_client
[ 85%] Linking CXX shared library libmousemove.so
[ 90%] Linking CXX shared library libclick.so
[ 95%] Linking CXX shared library libtype.so
[ 95%] Built target mousemove
[ 95%] Built target click
[100%] Linking CXX shared library libkey.so
[100%] Built target type
[100%] Built target key

**Comment by ReekyMarko** [comment]
It builds now for me but ydotoold is not working. It sees the client connecting but no keys are pressed

**Comment by ClassicOldSong** [comment]
> After that this issue came
> 
> $ make -j `nproc`
> Scanning dependencies of target ydotool_library
> Scanning dependencies of target ydotool_library_static
> [ 5%] Building CXX object CMakeFiles/ydotool_library.dir/Library/Instance.cpp.o
> [ 10%] Building CXX object CMakeFiles/ydotool_library.dir/Library/Tool.cpp.o
> [ 15%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Tool.cpp.o
> [ 20%] Building CXX object CMakeFiles/ydotool_library.dir/Library/libydotool.cpp.o
> [ 25%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/libydotool.cpp.o
> [ 30%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Instance.cpp.o
> [ 35%] Linking CXX shared library libydotool.so
> [ 40%] Linking CXX static library libydotool.a
> [ 40%] Built target ydotool_library
> [ 40%] Built target ydotool_library_static
> Scanning dependencies of target mousemove
> Scanning dependencies of target type
> Scanning dependencies of target key
> Scanning dependencies of target ydotoold
> Scanning dependencies of target click
> Scanning dependencies of target ydotool_client
> [ 45%] Building CXX object CMakeFiles/type.dir/Tools/Type/Type.cpp.o
> [ 50%] Building CXX object CMakeFiles/mousemove.dir/Tools/MouseMove/MouseMove.cpp.o
> [ 55%] Building CXX object CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o
> [ 60%] Building CXX object CMakeFiles/click.dir/Tools/Click/Click.cpp.o
> [ 65%] Building CXX object CMakeFiles/key.dir/Tools/Key/Key.cpp.o
> [ 70%] Building CXX object CMakeFiles/ydotool_client.dir/Client/ydotool.cpp.o
> /home/water/ydotool/Client/ydotool.cpp: In function ‘int socket_callback(uint16_t, uint16_t, int32_t, void*)’:
> /home/water/ydotool/Client/ydotool.cpp:83:1: warning: no return statement in function returning non-void [-Wreturn-type]
> }
> ^
> /home/water/ydotool/Client/ydotool.cpp: In function ‘int main(int, const char**)’:
> /home/water/ydotool/Client/ydotool.cpp:122:59: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
> instance->uInputContext->Init(&socket_callback, (void *)fd_client);
> ^~~~~~~~~
> [ 75%] Linking CXX executable ydotoold
> [ 80%] Linking CXX executable ydotool
> [ 80%] Built target ydotoold
> [ 80%] Built target ydotool_client
> [ 85%] Linking CXX shared library libmousemove.so
> [ 90%] Linking CXX shared library libclick.so
> [ 95%] Linking CXX shared library libtype.so
> [ 95%] Built target mousemove
> [ 95%] Built target click
> [100%] Linking CXX shared library libkey.so
> [100%] Built target type
> [100%] Built target key

It seems that build was success, these warnings could be ignored actually
