### ISSUE TITLE
Getting segmentation fault when using ydotool after the new update

### ISSUE THREAD

**Issue by shivindera** [ReimuNotMoe/ydotool#124]
On Manjaro (KDE) with latest aur build (git) I've got this issue when trying to use ydotool with the daemon.

Starting the daemon itself works fine:

```
> sudo ydotoold
ydotoold: listening on socket /tmp/.ydotool_socket
ydotoold: accepted client
```

But when running ydotool in another terminal, I get the below error:
```
> sudo ydotool key super+Ctrl+Left
ydotool: notice: unable to access ydotoold backend: failed to connect to socket: Connection refused
ydotool: you may experience device recognition delay issues
Next delay was set to 50 milliseconds.
Key delay was set to 12 milliseconds.
Repeat was set to 1 times.
Repeat delay was set to 20 milliseconds.
zsh: segmentation fault  sudo ydotool key super+Ctrl+Left
```

I saw a previous issue (#15) was fixed after a PR made in #18. Is this the same bug?

**Comment by techmunk** [comment]
I am also getting this on a fully up to date arch linux.

A build with commit e1334ae works fine, however building 6e18a32 causes a segfault.

**Comment by ClassicOldSong** [comment]
It seem #121 is what causing the problem. It's trying to manipulate with arguments that are passed to the `ydotool client` to add custom socket path ability but does nothing on the server side. Will revert the changes.

**Comment by shivindera** [comment]
Thank you works fine now!
