### ISSUE TITLE
Compiler warnings on Fedora-36 => errors

### ISSUE THREAD

**Issue by bhepple** [ReimuNotMoe/ydotool#129]
The compiler on f-36 is more particular and is upgrading warnings to error:

https://kojipkgs.fedoraproject.org//work/tasks/9476/82099476/build.log

I have had to add these flags to defeat the warnings, but that is not the wisest thing to do:

-Wno-error=stringop-overflow -Wno-error=sign-compare -Wno-error=maybe-uninitialized
-Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-result

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
