### ISSUE TITLE
Character swapped

### ISSUE THREAD

**Issue by t0fik** [ReimuNotMoe/ydotool#132]
After update to 1.0.0 `ydotool` started swapping characters, I found changing `]` -> `}`. Probably other characters are also affected.
Version 0.2.0 was not affected.

Steps to reproduce:
1. start `ydotoold`
2. in second terminal window execute `ydotool type ']'`
3. Typed value is `}`

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/4504f6d582019b3d63faf2a31a759b997a0e5fb8

**Comment by Carltoffel** [comment]
I have ydotool 1.0.1-2 installed via AUR and `ydotool type '^'` types `~`. Is this related or shall I open another issue with further details?

**Comment by t0fik** [comment]
Similar issue. I've created PR for that https://github.com/ReimuNotMoe/ydotool/pull/133
