### ISSUE TITLE
Seg fault from ydotoold on ubuntu repo

### ISSUE THREAD

**Issue by lostallmymoney** [ReimuNotMoe/ydotool#139]
ydotoold
ydotoold: listening on socket /tmp/.ydotool_socket
ydotoold: accepted client
Segmentation fault (core dumped)

**Comment by lostallmymoney** [comment]
Ubuntu 21.10
Wayland

**Comment by RJDan** [comment]
I am getting the same with Ubuntu 22.04.
ydotool /ydotoold from ubuntu repo (v0.1.8-3)

**Comment by lostallmymoney** [comment]
Hey I'm sorry I'm in a remote location right now, if you are trying to use ydotool I recommend writing everything as run commands so you don't get compatibility issues. I was working on a ydotool fix some time ago, I think I had to implement a way to get the ydotool server running.

Try compiling with a newer version of g++ (alpha or beta) and tell me about it !
________________________________

**Comment by dagelf** [comment]
For reference:
    
    ydotool        0.1.8-3      amd64        Command-line automation tool - cli

**Comment by dagelf** [comment]
Recompiling from this git repo works, so Debian version just needs to be repackaged:

    apt install scdoc
    git clone https://github.com/ReimuNotMoe/ydotool.git
    cd ydotool
    mkdir build
    cd build
    cmake ..
    make
    sudo ./ydotoold  &
    sudo chown $USER /tmp/.ydotool_socket
    ./ydotool mousemove -- -100 10 # test

**Comment by ReimuNotMoe** [comment]
It seems that you're using an older release of ydotool. Please build the latest version and see if the problem persists. Thanks.
