### ISSUE TITLE
Can't find `libboost_program_options` on Ubuntu

### ISSUE THREAD

**Issue by m93a** [ReimuNotMoe/ydotool#14]
I'm on Ubuntu 19.04 and I installed ydotool via the `.deb` file available in the Releases tab. I have the package [`libboost-program-options-dev`](https://packages.ubuntu.com/xenial/amd64/libboost-program-options-dev) installed, but I still get this error message:
```
ydotool: error while loading shared libraries: libboost_program_options.so.1.65.1: cannot open shared object file: No such file or directory
```
I tried installing also `libboost-program-options-dev:i386`, with no success.

**Comment by ClassicOldSong** [comment]
The deb file in the release tab currently only works on Ubuntu 18.04, you
should try compile it yourself on higher Ubuntu versions for now.

**Comment by ReimuNotMoe** [comment]
I'll set up a CI for this.

**Comment by ReimuNotMoe** [comment]
> I'm on Ubuntu 19.04 and I installed ydotool via the `.deb` file available in the Releases tab. I have the package [`libboost-program-options-dev`](https://packages.ubuntu.com/xenial/amd64/libboost-program-options-dev) installed, but I still get this error message:
> 
> ```
> ydotool: error while loading shared libraries: libboost_program_options.so.1.65.1: cannot open shared object file: No such file or directory
> ```
> 
> I tried installing also `libboost-program-options-dev:i386`, with no success.

Now you can download the packages from CI. See README.md
