### ISSUE TITLE
ydotool on Chrome OS

### ISSUE THREAD

**Issue by andrew521** [ReimuNotMoe/ydotool#142]
I was wondering if you guys could make ydotool work on chrome os. I have tried it and the daemon fails with "failed to open uinput device. No such file or directory." 

Although Chrome OS runs Debian 11 for crostini / Linux, it does not have /dev/uinput device.

**Comment by ClassicOldSong** [comment]
No that's not possible. The Linux environment under ChromeOS is basically a virtual machine, so it could have no ability to affect your host OS.
