### ISSUE TITLE
Issue with 1.0.1

### ISSUE THREAD

**Issue by mamantoha** [ReimuNotMoe/ydotool#143]
Hi!

This command works with version `0.2.0`:

```
ydotool key Ctrl+F8
```

But it doesn't work with the latest version.

Do I miss something?

**Comment by icxes** [comment]
From "ydotool key":

>Since there's no way to know how many keyboard layouts are there in the world,
we're using raw keycodes now.
>See `/usr/include/linux/input-event-codes.h' for available key codes (KEY_*).

What you want is:
ydotool key 29:1 66:1 29:0 66:0

**Comment by mamantoha** [comment]
@icxes got it. Thanks.
