### ISSUE TITLE
can't find  "super" 

### ISSUE THREAD

**Issue by kissunyeason** [ReimuNotMoe/ydotool#145]
I can't find the code of the "super" key in input-event-codes.h, what is its numeric code?

**Comment by kissunyeason** [comment]
Meta

**Comment by ElectricRCAircraftGuy** [comment]
KEY_LEFTMETA, key 125. 

I wrote a full tutorial on my website here: https://gabrielstaples.com/ydotool-tutorial/#gsc.tab=0

See https://github.com/ReimuNotMoe/ydotool/issues/207#issue-1762095867
