### ISSUE TITLE
Manpages need to be updated since the refactor

### ISSUE THREAD

**Issue by rieje** [ReimuNotMoe/ydotool#147]
Manpages need to be updated since the refactor, e.g. usage for [ydotool key](https://github.com/ReimuNotMoe/ydotool/blob/master/Client/tool_key.c#L39). 

I thought ydotool was broken just following the example from `man ydotool(1)`:

> Example: Switch to tty1:
               ydotool key ctrl+alt+f1

which doesn't do anything, especially because it exits with success.

**Comment by ClassicOldSong** [comment]
The man page is now updated.
