### ISSUE TITLE
Circonflex character is typed out as tilda

### ISSUE THREAD

**Issue by gl4eqen** [ReimuNotMoe/ydotool#150]
To reproduce:
```sh
$ ydotool type '^'
```

Effect:
```
~
```

Expected result:
```
^
```

_Send help._ Thanks in advance!

**Comment by firecat53** [comment]
PR #133 to fix this was posted in Feb 2022.

**Comment by Glaeqen** [comment]
@ReimuNotMoe is there any hope in getting that patch in? I see that you are somewhat active on GH.

**Comment by ReimuNotMoe** [comment]
Merged.
