### ISSUE TITLE
Running without sudo?

### ISSUE THREAD

**Issue by Ashark** [ReimuNotMoe/ydotool#154]
Readme says:
> This program requires access to /dev/uinput. This **usually** requires root permissions.

But what are _unusual_ cases?

I tried to give others rw: `chmod o+rw /dev/uinput`, but that did not help.

Is there any way to not require sudo? Maybe something to do with socket permissions? Or with adding user to some group?

The sudo requirement is a problem for me, because I want to assign a command chain to a single shortcut via kde, but it cannot (currently) execute sudo commands, as I could say.

**Comment by sqozz** [comment]
Actually if you run a "full blown desktop" you should not need to require root and adding your user to the "uinput" group should give you enough access to make use of ydotool without root.

**Comment by Ashark** [comment]
I am in `input` group and it is working now. Cannot say for sure what I did.
I can mention my solution with suid that I found: https://unix.stackexchange.com/a/703049/264065
But as it is now working without it, it is not needed anymore.

**Comment by ElectricRCAircraftGuy** [comment]
I run the the daemon with sudo, but not the main tool. I describe how here: https://gabrielstaples.com/ydotool-tutorial/#gsc.tab=0

See https://github.com/ReimuNotMoe/ydotool/issues/207#issue-1762095867
