### ISSUE TITLE
Failed to run `ydotoold`: failed to bind socket: Address already in use

### ISSUE THREAD

**Issue by nlpsuge** [ReimuNotMoe/ydotool#161]
$ ydotoold
failed to bind socket: Address already in use
fish: Job 1, 'ydotoold' terminated by signal SIGABRT (Abort)

I can't find any process related to `ydotoold` in the `ps -ef` and `netstats -lnpa`. So I don't know which app is using the port that ydotool uses.

**Comment by nlpsuge** [comment]
And how I know which address and port are used by `ydotool`? Maybe you could also log those two info along with `failed to bind socket: Address already in use`?

**Comment by grigio** [comment]
+1 I'm having the same issue

**Comment by richo67** [comment]
Need to delete socket from /tmp
```sudo rm -rf /tmp/.ydotool_socket```

**Comment by richo67** [comment]
I looked at the manual of this tool, as we all should do and found the solution:

```
*--socket-path arg*  _<path>_
	Socket path (default: /tmp/.ydotool_socket)

*--socket-perm arg* _<perms>_
	Socket permission (default: 0600)
```

**Comment by hugeblank** [comment]
> I looked at the manual of this tool, as we all should do and found the solution:
> 
> ```
> *--socket-path arg*  _<path>_
> 	Socket path (default: /tmp/.ydotool_socket)
> 
> *--socket-perm arg* _<perms>_
> 	Socket permission (default: 0600)
> ```

I don't see how these are related to the solution, you didn't provide what the arguments should be changed to. Or are you just saying that the default values are the problem?

**Comment by richo67** [comment]
Well, I assume, that should be quite simple.

If you use option --socket-perm and you extend permission to write also for your user group, than this socket file, if existed after crash of ydotoold could be removed and recreated also by other user.

Depends how do you start the daemon ydotoold you can also place the socket into your own user's temporary folder, or leave it in /tmp (which is cleaned up at the systems reboot) and name it with your user name in it and writing permission for your user so you can also clean it after ydotoold restarts or starts again after crash.

**Comment by JohnGebbie** [comment]
You can see my attempt to package ydotool so that wouldn't require root here: https://github.com/void-linux/void-packages/pull/39920

It took enough patching that I ended up writing another tool called [dotool](https://git.sr.ht/~geb/dotool) instead.

**Comment by ReimuNotMoe** [comment]
The socket error handling is improved and more user friendly in the latest release. Please test it and report any more problems in a new issue.

**Comment by nlpsuge** [comment]
> if I run it as user then it will restart few times with message `failed to open uinput device: Permission denied` until I log in and than socket will be created as:

You might need to start the `ydotoold` using `systemctl --user` so ydotoold will run under the normal user, like

`systemctl --user enable ydotool.service`
and
`systemctl --user start ydotool.service`

I'm using `ydotool` to send shortcuts to a window under normal user, for more info see https://github.com/nlpsuge/gnome-shell-extension-another-window-session-manager#how-to-make-close-by-rules-work.

Rencently, `ydotool` works not very well though. `systemctl --user status ydotool.service` shows it's not running sometimes.
