### ISSUE TITLE
[feature request] What version do I have?

### ISSUE THREAD

**Issue by donjan** [ReimuNotMoe/ydotool#169]
Running on Ubuntu 22.04.
Since the distribution repository version is faulty, I have to once or twice per year pull the binary from the [releases page](https://github.com/ReimuNotMoe/ydotool/releases). But right now I have no idea if I'm using 1.0.0 or already 1.0.1.
`ydotool debug` doesn't tell me much, `ydotool help` doesn't show the version, and there is no `ydotool --version`, `ydotool -v` or `ydotool version`.

**Comment by ReimuNotMoe** [comment]
Implemented in https://github.com/ReimuNotMoe/ydotool/commit/fe91c1fb31fd12cc530c8c3e7d9d09a932099086
