### ISSUE TITLE
Ability to record input?

### ISSUE THREAD

**Issue by shmerl** [ReimuNotMoe/ydotool#17]
Is there a way to record input for ydootol, to replay it later?

One example where it can be useful is automated benchmarkng for games. I.e. consider such scenario:

1. Start the game, then record the input while you perform certain actions that you want to benchmark.
2. Start the game again, and replay the input. Capture performance metrics logs.

This can create a way to run a reproducible benchmark for any game, but recording part is quite critical, since you can't really manually construct such input.

**Comment by ReimuNotMoe** [comment]
This is possible, I'll work on this when I have more time.

**Comment by ReimuNotMoe** [comment]
Now this is implemented.

https://github.com/ReimuNotMoe/ydotool/commit/3572cbe4f580a3741c13372fd5fb500b079c4151

**Comment by shmerl** [comment]
Thanks! Would be good to document how to use that, otherwise it's somewhat obscure.
