### ISSUE TITLE
stdin file argument support lost in rewrite

### ISSUE THREAD

**Issue by vaygr** [ReimuNotMoe/ydotool#172]
Doesn't seem to work with the latest (**1.0.1**) release:

```
ydotool type --file -
ydotool: type: error: failed to open -: No such file or directory
```

edit: `--file /dev/stdin` works as a workaround though.

**Comment by ReimuNotMoe** [comment]
It's supposed to be fixed in #137 

Please report if the problem persists. Thanks.
