### ISSUE TITLE
Caret ^ gets typed as tilde ~

### ISSUE THREAD

**Issue by BoostCookie** [ReimuNotMoe/ydotool#173]
ydotool converts carets ^ to a tildes ~ when typing.
```sh
$ ydotool type "test^dude"
test~dude%
```

**Comment by firecat53** [comment]
PR #133 (from Feb 2022) outstanding to fix it.

**Comment by elder-n00b** [comment]
I just had a `#` turned into `£` by the way.
I have no idea if it depends on the locale used (it_IT.UTF8 here).

**Comment by BoostCookie** [comment]
I can confirm that it is fixed in the current git commit. Just waiting for a proper release now.
