### ISSUE TITLE
ydotool: notice: ydotoold backend unavailable (may have latency+delay issues)

### ISSUE THREAD

**Issue by VictorGimenez** [ReimuNotMoe/ydotool#179]
Hello there,

I have installed ydotool today, and after execute `ydotool mousemove 50 50` I got the following error:
`$ydotool mousemove 50 50
ydotool: notice: ydotoold backend unavailable (may have latency+delay issues)
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open uinput device
Aborted
`

When I executed with `sudo` I got only:
`$sudo ydotool mousemove 50 50
ydotool: notice: ydotoold backend unavailable (may have latency+delay issues)` 

With ydotoold:
`ydotoold: listening on socket /tmp/.ydotool_socket)`
And nothing is done.

How could I fix this issue?

**Comment by ReimuNotMoe** [comment]
It seems that you're using an older release of ydotool. Please build the latest version and see if the problem persists. Thanks.

**Comment by VictorGimenez** [comment]
Hi @ReimuNotMoe, sorry for the late reply, I was feeling discouraged after it and I was trying to find another approach and I found in python the uinput package, but I decided to come back here and explore better ydotool... I realized that this message doesn't look like to be a error, and it's a warning information but even so nothing happens with the mouse cursor. I installed ydotool through ```sudo apt install ydotool``` before, where could I find his version? Thanks

**Comment by VictorGimenez** [comment]
Hey there, finally I solved it!! I was able to install and build ydotool!

**Comment by novoid** [comment]
> Hey there, finally I solved it!! I was able to install and build ydotool!

Care to explain how you solved it?
