### ISSUE TITLE
Man page needs corrections

### ISSUE THREAD

**Issue by bertulli** [ReimuNotMoe/ydotool#181]
Hi!
First, thanks for your work. I've noticed that the `man` page for `ydotool.1` still lists the usage of `recorder`, which, IIUC from [this PR](https://github.com/ReimuNotMoe/ydotool/pull/130), has being detached as a separate project. I think it needs a correction.

Thanks!

**Comment by ClassicOldSong** [comment]
Recorder in man page is removed now
