### ISSUE TITLE
feature request: add the below to the manual for us noobs

### ISSUE THREAD

**Issue by zombiehoffa** [ReimuNotMoe/ydotool#189]
Hi,

If you could add the following to the manual it should help noobs save a lot of time, as wev does not give the uiinput key numbers but libinput record does.

You can find the key name/number your keyboard is sending to libinput by running sudo ibinput record and then selecting your keyboard from the list it will show you the lib input proper key name and number for each key you press.

**Comment by ReimuNotMoe** [comment]
Added in https://github.com/ReimuNotMoe/ydotool/commit/43b1a11fe3aff3a50673db8096f87355c4b16525, thanks
