### ISSUE TITLE
Improve documentation / ydotool aborts without daemon running

### ISSUE THREAD

**Issue by leg7** [ReimuNotMoe/ydotool#190]
Maybe I'm missing something but it is not mentioned anywhere that ydotool requires the ydotoold daemon to be running for it to work. I had to figure this out on my own.  Maybe this is a bug and ydotoold is not required?

If I run `ydotool type test` without the daemon running this is the output:
```
failed to connect socket: Connection refused
Aborted (core dumped)
```
when the daemon is running this error doesn't happen and ydotool works properly.

I'm running hyprland.
```
Hyprland, built from branch main at commit 32d56fec977b109aeecb06288a1b45cfe6b83117dirty (feat: border angle animations (1469)).
flags: (if any)
```

I suspect this has something to do with YDOTOOL_SOCKET not being set?

**Comment by ClassicOldSong** [comment]
There's a note in the README saying 

```

Since v1.0.0, the use of ydotoold is mandatory.

```
