### ISSUE TITLE
Xvfb support?

### ISSUE THREAD

**Issue by galdwd** [ReimuNotMoe/ydotool#194]
I have a headless Debian 11 VM I wanted to use for testing with ydotool, but it seems like ydotool's virtual mouse and keyboard are not being registered for xvfb, they're not listed from `xinput list` under display `:1`. Is this a known limitation, or is there an extra step necessary for xvfb that I missed?

**Comment by ClassicOldSong** [comment]
As answered [here](https://unix.stackexchange.com/questions/665668/mouse-doesnt-work-on-xvfb), it seems xvfb doesn't support any physical input devices. Since ydotool emulates a real keyboard and mouse, it's a physical input device to your desktop environments, thus xvfb won't recognize.
