### ISSUE TITLE
Help on running ydotoold

### ISSUE THREAD

**Issue by exup** [ReimuNotMoe/ydotool#198]
I am not understanding how to get ydotool running under wayland.
Im not clear on the step to run the ydotoold as a daemon service as I get the message

ydotool key F1
"failed to connect socket `/run/user/1000/.ydotool_socket': No such file or directory"

User is a member of the input group.

**Comment by Thomas-git** [comment]
You can reload systemd deamons with
`systemctl daemon-reload`
then enable ydotoold and start it
`systemctl enable ydotoold'
`systemctl start ydotoold'

But... it stills failed with the same error message.
`systemctl status ydotool` shows 
```● ydotool.service - Starts ydotoold service
     Loaded: loaded (/usr/lib/systemd/system/ydotool.service; enabled; preset: disabled)
     Active: active (running) since Mon 2023-04-10 11:11:49 CEST; 15s ago
   Main PID: 22237 (ydotoold)
      Tasks: 1 (limit: 38164)
     Memory: 168.0K
        CPU: 4ms
     CGroup: /system.slice/ydotool.service
             └─22237 /usr/bin/ydotoold

avril 10 11:11:49 air-mite systemd[1]: Started ydotool.service - Starts ydotoold service.
```
So I don't know what else to do. ydotool seems to be looking for the socket in the wrong place.

**Comment by codeonblocks** [comment]
You have to start it up first before you can do it.

To do this, open a terminal and type

```bash
$ sudo ydotoold
```

Then, open another terminal while you keep that first one open and type whatever commands you want.

**Comment by exup** [comment]
Hi, ok seems to work if you run it as sudo, I was under the impression it could be launched by a user. Although not ideal, I can use this as it is. Start the process, monitor it then shut it down.

**Comment by ElectricRCAircraftGuy** [comment]
I wrote a full tutorial on my website here: https://gabrielstaples.com/ydotool-tutorial/#gsc.tab=0

See https://github.com/ReimuNotMoe/ydotool/issues/207#issue-1762095867

**Comment by shellheim** [comment]
Just in case someone comes across the same problem again, https://gist.github.com/shellheim/f00b5fe18f6217d990292a2f8f06b78a
