### ISSUE TITLE
fork ydotoold

### ISSUE THREAD

**Issue by carnager** [ReimuNotMoe/ydotool#20]
When using ydotoold in scripts one has to start the daemon using `ydotoold&`. When using `ydotool type` too quickly this results in a few characters being lost. It would be nice if the ydotool daemon actually forks once it's started to make handling easier.

**Comment by ClassicOldSong** [comment]
This makes no sense. It takes time for the kernel to recognize the new input device, so forking causes exactly the same issue of missing characters.
What you should do is making ydotoold running as a daemon such as using systemd and then use ydotool as usual in your script.

**Comment by carnager** [comment]
Of course I meant forking after it successfully started. Like e.g. mpd does.
