### ISSUE TITLE
ydotoold : segmentation fault (core dumped)

### ISSUE THREAD

**Issue by lm2lm2** [ReimuNotMoe/ydotool#201]
hello
Im a long time user of xdotool, very satisfied until using it on some webforms, through chrome/iridium/firefox : after few hours, xdotool makes the browser crash. Im using in background anydesk and nomachine.
however, I tried several times the ydotool alternative, until ydotoold was root-started :
ydotoold: listening on socket /tmp/.ydotool_socket
ydotoold: accepted client
Erreur de segmentation [segmentation fault] (core dumped)

since this (reported last week on their project git), I have no idea to do, and I mostly see that Im far of it not the only one to get stuck by a core dumped/segfault. I dont know where does it comes, Im running it on LMDE5 fresh install, Id like to get xdotool or ydotool running well (please notice Im still with xorg), but to get a program whom crashes at almost every commands (just did one or two " ydotool key 56:1 62:1 62:0 56:0 ydotool: notice: ydotoold backend unavailable (may have latency+delay issues)" commands in terminal to have it crashed makes me a bit misunderstanding if Im supposed to go on that new software.

And in fact, I just dont know how to solve this..

**Comment by lm2lm2** [comment]
solved by using the last version, more information on :
https://www.linuxquestions.org/questions/linux-software-2/ydotool-anyone-really-succeed-to-make-it-work-4175725009/

**Comment by ElectricRCAircraftGuy** [comment]
Since it's solved you should close this issue.

**Comment by Paiusco** [comment]
@ReimuNotMoe feel free to close this one :)
