### ISSUE TITLE
keydown and keyup implementation

### ISSUE THREAD

**Issue by Bruce-YC** [ReimuNotMoe/ydotool#21]
Any plan to implement these features from the xdotool? These would be immensely helpful for actions such as app cycling.

**Comment by ReimuNotMoe** [comment]
Yes, this is planned. I'll be working on this in a few days.

**Comment by itsyoshio** [comment]
+1

**Comment by Bruce-YC** [comment]
Any update?

**Comment by ReimuNotMoe** [comment]
> Any update?

Sorry for the long delay.

https://github.com/ReimuNotMoe/ydotool/commit/dedec0b95c32ddd305e228c23f3220283f0643b3

You should use this feature in conjunction with `ydotoold` or `--persist-delay`.
