### ISSUE TITLE
Why CMake is halted at 3.4?

### ISSUE THREAD

**Issue by Paiusco** [ReimuNotMoe/ydotool#225]
Main question is why, and to understand what is blocking ydotool to update the cmake version. 
Currently, it builds on `ubuntu:latest` which is 22.04 having cmake 3.22

I'm open to send a PR as long the update is accepted. Which distros are we basing on to block the CMake update?

CMake 3.28.3 is already sending a warning saying: 
```
Compatibility with CMake < 3.5 will be removed from a future version of CMake.
``` 

As a side question, why not update the C standard to 2011 as well?

**Comment by ReimuNotMoe** [comment]
>what is blocking ydotool to update the cmake version

Nothing I guess.

Please open a PR if you have the time, thx
