### ISSUE TITLE
Why use systemd user service and not systemd?

### ISSUE THREAD

**Issue by Paiusco** [ReimuNotMoe/ydotool#228]
I'm used to installing the service files into /lib/systemd/system/ and be able to control only through there.

Why is it hard-coded to install on `systemduserunitdir` and not `systemdsystemunitdir`? Security? Does systemd look into user services during boot, even if it doesn't know which user are you?

I was thinking about having also an option to be able to define where to install the service file, but it seems a bit ugly and I don't have any other project to use as a good example, so I'd like to discuss it.

**Comment by Paiusco** [comment]
If we move the app towards being a systemd system service instead of user, would we remove all the clutter of having the need to add yourself as a `input` group user and add a extra udev rule?

I haven't tested it, but I have the feeling that ydotoold running as root is just fine if the client can talk to the daemon

**Comment by ReimuNotMoe** [comment]
Stuff in this repo other than the C code are not written by me and I have no idea about how they work.

You can submit a PR and I'll merge it.

**Comment by Paiusco** [comment]
Thanks @ReimuNotMoe, I'm thinking about a nice way to solve that and keep it as an user service for now on systemd. Maybe defining the socket path at compile time on the service file... I may submit a PR then. This ticket can be closed for now
