### ISSUE TITLE
Compiling/installation issue

### ISSUE THREAD

**Issue by volt4ire** [ReimuNotMoe/ydotool#23]
I'm trying to compile and install ydotool on Ubuntu 19.04 but am getting the following error after following the build instructions and running make -j `nproc`:

`Scanning dependencies of target ydotool_library_static
Scanning dependencies of target ydotool_library
[  5%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Instance.cpp.o
[ 10%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Tool.cpp.o
[ 15%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/libydotool.cpp.o
[ 20%] Building CXX object CMakeFiles/ydotool_library.dir/Library/libydotool.cpp.o
[ 25%] Building CXX object CMakeFiles/ydotool_library.dir/Library/Tool.cpp.o
[ 30%] Building CXX object CMakeFiles/ydotool_library.dir/Library/Instance.cpp.o
[ 35%] Linking CXX static library libydotool.a
[ 35%] Built target ydotool_library_static
[ 40%] Linking CXX shared library libydotool.so
[ 40%] Built target ydotool_library
Scanning dependencies of target type
Scanning dependencies of target click
Scanning dependencies of target key
Scanning dependencies of target ydotoold
[ 45%] Building CXX object CMakeFiles/type.dir/Tools/Type/Type.cpp.o
[ 50%] Building CXX object CMakeFiles/key.dir/Tools/Key/Key.cpp.o
[ 55%] Building CXX object CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o
[ 60%] Building CXX object CMakeFiles/click.dir/Tools/Click/Click.cpp.o
/home/rwbarat/ydotool/Tools/Key/Key.cpp: In function ‘std::vector<int> KeyStroke2Code(const string&)’:
/home/rwbarat/ydotool/Tools/Key/Key.cpp:73:16: error: ‘Table_ModifierKeys’ was not declared in this scope
auto t_kms = Table_ModifierKeys.find(it);
^~~~~~~~~~~~~~~~~~
/home/rwbarat/ydotool/Daemon/ydotoold.cpp: In function ‘int client_handler(int)’:
/home/rwbarat/ydotool/Daemon/ydotoold.cpp:31:2: error: ‘uInputRawData’ was not declared in this scope
uInputRawData buf{0};
^~~~~~~~~~~~~
/home/rwbarat/ydotool/Daemon/ydotoold.cpp:34:22: error: ‘buf’ was not declared in this scope
int rc = recv(fd, &buf, sizeof(buf), MSG_WAITALL);
^~~
make[2]: *** [CMakeFiles/ydotoold.dir/build.make:63: CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/ydotoold.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/key.dir/build.make:63: CMakeFiles/key.dir/Tools/Key/Key.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/key.dir/all] Error 2
[ 65%] Linking CXX shared library libclick.so
[ 70%] Linking CXX shared library libtype.so
[ 70%] Built target click
[ 70%] Built target type
make: *** [Makefile:152: all] Error 2`

**Comment by ssendev** [comment]
I have the same issue on fedora 30. i installed the libevdevPlus and libuInputPlus release rpms but the ydotool rpm complains about the boost version since i have 1.69.0. (it also complains that nothing provides libevdevPlus.so.0 and libuInputPlus.so.0 even though i installed the rpms)

trying to compile ydootool results in
```
Scanning dependencies of target ydotool_library_static
[ 10%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/libydotool.cpp.o
[ 25%] Built target ydotool_library
[ 30%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Tool.cpp.o
[ 35%] Building CXX object CMakeFiles/ydotool_library_static.dir/Library/Instance.cpp.o
Scanning dependencies of target ydotoold
Scanning dependencies of target click
Scanning dependencies of target type
Scanning dependencies of target mousemove
Scanning dependencies of target ydotool_client
[ 45%] Building CXX object CMakeFiles/type.dir/Tools/Type/Type.cpp.o
[ 45%] Building CXX object CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o
[ 50%] Building CXX object CMakeFiles/click.dir/Tools/Click/Click.cpp.o
[ 55%] Building CXX object CMakeFiles/key.dir/Tools/Key/Key.cpp.o
[ 60%] Building CXX object CMakeFiles/mousemove.dir/Tools/MouseMove/MouseMove.cpp.o
[ 65%] Building CXX object CMakeFiles/ydotool_client.dir/Client/ydotool.cpp.o
/home/kaworu/ext-dev/ydotool/Daemon/ydotoold.cpp: In function ‘int client_handler(int)’:
/home/kaworu/ext-dev/ydotool/Daemon/ydotoold.cpp:31:2: error: ‘uInputRawData’ was not declared in this scope
   31 |  uInputRawData buf{0};
      |  ^~~~~~~~~~~~~
/home/kaworu/ext-dev/ydotool/Tools/Key/Key.cpp: In function ‘std::vector<int> KeyStroke2Code(const string&)’:
/home/kaworu/ext-dev/ydotool/Tools/Key/Key.cpp:73:16: error: ‘Table_ModifierKeys’ was not declared in this scope
   73 |   auto t_kms = Table_ModifierKeys.find(it);
      |                ^~~~~~~~~~~~~~~~~~
/home/kaworu/ext-dev/ydotool/Daemon/ydotoold.cpp:34:22: error: ‘buf’ was not declared in this scope
   34 |   int rc = recv(fd, &buf, sizeof(buf), MSG_WAITALL);
      |                      ^~~
/home/kaworu/ext-dev/ydotool/Client/ydotool.cpp: In function ‘int socket_callback(uint16_t, uint16_t, int32_t, void*)’:
/home/kaworu/ext-dev/ydotool/Client/ydotool.cpp:75:2: error: ‘uInputRawData’ was not declared in this scope
   75 |  uInputRawData buf{0};
      |  ^~~~~~~~~~~~~
/home/kaworu/ext-dev/ydotool/Client/ydotool.cpp:76:2: error: ‘buf’ was not declared in this scope
   76 |  buf.type = type;
      |  ^~~
/home/kaworu/ext-dev/ydotool/Client/ydotool.cpp: In function ‘int main(int, const char**)’:
/home/kaworu/ext-dev/ydotool/Client/ydotool.cpp:124:78: error: no matching function for call to ‘uInputPlus::uInput::Init(int (*)(uint16_t, uint16_t, int32_t, void*), void*)’
  124 |   instance->uInputContext->Init(&socket_callback, (void *)(intptr_t)fd_client);
      |                                                                              ^
In file included from /home/kaworu/ext-dev/ydotool/Client/../CommonIncludes.hpp:36,
                 from /home/kaworu/ext-dev/ydotool/Client/ydotool.hpp:17,
                 from /home/kaworu/ext-dev/ydotool/Client/ydotool.cpp:13:
/usr/include/uInputPlus/uInput.hpp:44:7: note: candidate: ‘void uInputPlus::uInput::Init(const uInputPlus::uInputSetup&)’
   44 |  void Init(const uInputSetup &setup);
      |       ^~~~
/usr/include/uInputPlus/uInput.hpp:44:7: note:   candidate expects 1 argument, 2 provided
make[2]: *** [CMakeFiles/ydotoold.dir/build.make:63: CMakeFiles/ydotoold.dir/Daemon/ydotoold.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:147: CMakeFiles/ydotoold.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 70%] Linking CXX static library libydotool.a
make[2]: *** [CMakeFiles/ydotool_client.dir/build.make:63: CMakeFiles/ydotool_client.dir/Client/ydotool.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:332: CMakeFiles/ydotool_client.dir/all] Error 2
[ 70%] Built target ydotool_library_static
make[2]: *** [CMakeFiles/key.dir/build.make:63: CMakeFiles/key.dir/Tools/Key/Key.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/key.dir/all] Error 2
[ 75%] Linking CXX shared library libtype.so
[ 80%] Linking CXX shared library libclick.so
[ 85%] Linking CXX shared library libmousemove.so
[ 85%] Built target click
[ 85%] Built target type
[ 85%] Built target mousemove
make: *** [Makefile:152: all] Error 2
```

**Comment by ReimuNotMoe** [comment]
Looks like there's a version mismatch.

For now, you could just use the static version of the binary. Because I don't know how to do packaging properly...

**Comment by ssendev** [comment]
The static version works. Though `ydotoold` is missing but that's a minor detail since it's not required.

Thanks for the static version and ydotool in general.
