### ISSUE TITLE
Why the rewrite in JavaScript and not (insert another language)?

### ISSUE THREAD

**Issue by Paiusco** [ReimuNotMoe/ydotool#235]
I saw the note that the whole tool will be rewritten in JavaScript, but considering it'll be rewritten anyway have you considered Rust, and if not, why JavaScript? (I had to add [the meme](https://transitiontech.ca/random/RIIR)) 

I understand you're probably already working on it, but I wonder if writing it on Rust, a language which has a very active and growing community, wouldn't be also helpful to grow the project even further?

I also know that probably raising this question and pointing it to Rust may cause someone to come and ask to be rewritten in D, or Zig, or whatnot.

**Comment by ClassicOldSong** [comment]
Rust still needs time for it to become mature. So do other languages you mentioned above.

We value real usability over hype.

**Comment by crabdancing** [comment]
Rust is completely mature. And the fact that it's correctness-focused and high performant makes it a better starting point for core infrastructure IMO. You can make JS bindings p. easily if you want, so the usability argument seems like bunk.

If e.g. someone wants to use a Rust-powered `ydotool-lib` or whatever to make a Wayland-compatible VNC, they actually could -- and it would basically never crash, and be as close to perfect as possible, and scale up and down as much as you need, and embed and optimize down as much as you need.

But I get that you're not going for universality. Which I guess means more code dupe and ecosystem fracturing. :woman_shrugging: Quite a shame.

**Comment by ClassicOldSong** [comment]
People don't share a same mindset. Rust's correctness might be suitable for you, but it's also a burden of productivity for us. We would pay way too much unnecessary efforts to satisfy Rust's "correctness" that we can achieve already by ourselves in exchange for the little to no benefit Rust could provide to us.

**Comment by Secret-chest** [comment]
Why not just keep C?

**Comment by ClassicOldSong** [comment]
The project will speak for itself when it's done.

**Comment by Paiusco** [comment]
Can you consider review the PR list? And after it do a proper release before the rewrites takes place?
