### ISSUE TITLE
Possible to type in specific window?

### ISSUE THREAD

**Issue by lillian-b** [ReimuNotMoe/ydotool#236]
With `xdotool` I can pass a `--window`  argument to specify which window I want to send keystrokes to. Is this possible in `ydotool`? Thanks

**Comment by ClassicOldSong** [comment]
ydotool works differently than xdotool where ydotool simulates a keyboard but xdotool taps into the X server. That’s how ydotool can work universally but xdotool can’t. So it’s not possible for ydotool to type only to one specific window without the window being focused.

**Comment by thepragmaticmero** [comment]
could it be fixed with the "global shortcuts" implementation of wayland? I'm pretty interested in that rlly? mmmm
