### ISSUE TITLE
error while loading shared libraries: libuInputPlus.so.0: No such file or directory

### ISSUE THREAD

**Issue by pawamoy** [ReimuNotMoe/ydotool#24]
I successfully compiled and installed the three listed dependencies. Then I successfully built and installed `ydotool`. But when I run it I get this error:

```console
$ ydotool
ydotool: error while loading shared libraries: libuInputPlus.so.0: cannot open shared object file: No such file or directory
```

I'm on ArchLinux (1.4? ArchLabs 2019.1.20)

**Comment by ReimuNotMoe** [comment]
These libraries will be installed to `/usr/local/lib` by default. Check if your distro lookup libraries in that path. Or simply link them to `/usr/lib`.

**Comment by pawamoy** [comment]
Thanks. Solved with

```
sudo ln -s /usr/local/lib/libuInputPlus.so.0 /usr/lib/
sudo ln -s /usr/local/lib/libydotool.so /usr/lib/
sudo ln -s /usr/local/lib/libevdevPlus.so.0 /usr/lib/
```

**Comment by ReimuNotMoe** [comment]
Now static binaries are also provided in releases.

**Comment by patrigg** [comment]
Thanks for working on this issue. Sadly the static version of the client does not build anymore. It tries to link against uInputPlus dynamically and statically, here is the linker invocation generated by cmake:
`/usr/bin/c++    -rdynamic CMakeFiles/ydotool_client_static.dir/Client/ydotool.cpp.o  -o ydotool_static libydotool.a -lboost_program_options -lpthread -luInputPlus -levdevPlus -static -ldl -lboost_program_options -luInputPlus -levdevPlus `

On my distribution (ArchLinux), there are no static versions of these libraries installed and the PKGBUILD does not require static versions. I tried to patch the PKGBUILD by only making the dynamic versions. However, the "install" make tries to build and install the static versions as well, which fail to build.
Could you provide an install target for the dynamic versions only, making the static versions optional?

**Comment by ReimuNotMoe** [comment]
> Thanks for working on this issue. Sadly the static version of the client does not build anymore. It tries to link against uInputPlus dynamically and statically, here is the linker invocation generated by cmake:
> `/usr/bin/c++ -rdynamic CMakeFiles/ydotool_client_static.dir/Client/ydotool.cpp.o -o ydotool_static libydotool.a -lboost_program_options -lpthread -luInputPlus -levdevPlus -static -ldl -lboost_program_options -luInputPlus -levdevPlus `
> 
> On my distribution (ArchLinux), there are no static versions of these libraries installed and the PKGBUILD does not require static versions. I tried to patch the PKGBUILD by only making the dynamic versions. However, the "install" make tries to build and install the static versions as well, which fail to build.
> Could you provide an install target for the dynamic versions only, making the static versions optional?

This should be fixed now, see #27

**Comment by buddha231** [comment]
I tried all this:
sudo ln -s /usr/local/lib/libuInputPlus.so.0 /usr/lib/
sudo ln -s /usr/local/lib/libydotool.so /usr/lib/
sudo ln -s /usr/local/lib/libevdevPlus.so.0 /usr/lib/

But yet it shows the error:
ydotool: error while loading shared libraries: libydotool.so: cannot open shared object file: No such file or directory
![Screenshot from 2020-05-25 12-03-29](https://user-images.githubusercontent.com/52292457/82784236-d2080e80-9e7f-11ea-8cc4-24ad880955f0.png)

**Comment by buddha231** [comment]
> I tried all this:
> sudo ln -s /usr/local/lib/libuInputPlus.so.0 /usr/lib/
> sudo ln -s /usr/local/lib/libydotool.so /usr/lib/
> sudo ln -s /usr/local/lib/libevdevPlus.so.0 /usr/lib/
> 
> But yet it shows the error:
> ydotool: error while loading shared libraries: libydotool.so: cannot open shared object file: No such file or directory
> ![Screenshot from 2020-05-25 12-03-29](https://user-images.githubusercontent.com/52292457/82784236-d2080e80-9e7f-11ea-8cc4-24ad880955f0.png)
> 
> I'm on Ubuntu 20.04 LTS
![image](https://user-images.githubusercontent.com/52292457/82791100-e272b600-9e8c-11ea-810b-f84615781ae6.png)
