### ISSUE TITLE
ydotoold at reboot: "a password is required"

### ISSUE THREAD

**Issue by michas79de** [ReimuNotMoe/ydotool#253]
Hi!

I'm using Ubuntu 24.04.1 LTS with GNOME 46.
After setting up  sSMTP 2.64, I'm able to receive emails from my system from jobs, timed by cron.daily or so.

But it also sent me this warning per mail after reboot:
`<myhost> : Oct  8 21:17:02 : <myuser> : a password is required ; PWD=/home/<myuser> ; USER=root ; COMMAND=/usr/local/bin/ydotoold --socket-path=$HOME/.ydotool_socket '--socket-own=$(id -u):$(id -g)'`

In Autostart I have the command line:
`sudo -b ydotoold --socket-path="$HOME/.ydotool_socket" --socket-own="$(id -u):$(id -g)"
`
But I have to admit, I don't know anymore, why I have this line.
So is this correct or is it a bug and what can I do to avoid this message after system starts?

**Comment by Paiusco** [comment]
- which version of the package you have?
- If you're using Ubuntu, I imagine that you're using systemd, wouldn't you prefer to use the `.service` file provided by `ydotoold`?

I understand the message, as if you want to run something as root from your own user, you'll need to add the password, or edit your `sudoers` file

**Comment by michas79de** [comment]
ydotool 0.1.8-3build1
ydotoold 1.0.4-0-g57ba7d0

I wasn't able to find the autostart command line at google, but it definitely did not came out of my brain. So I don't know, what I should prefer.
But not knowing, why it's there, I'll try without it for a while...
(Maybe it's a leftover from my search for some alternative tools after leaving windows.)
