### ISSUE TITLE
Provide static binaries

### ISSUE THREAD

**Issue by NilsIrl** [ReimuNotMoe/ydotool#26]
`ydotool` can be quite annoying to install especially due to the fact it relies on 2 libraries which aren't commonly used.

It would be nice if the release section provided more up to date binaries and binaries that are statically linked with `libuInputPlus.so.0` and `libevdevPlus.so.0`

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/releases/tag/v0.1.6

**Comment by NilsIrl** [comment]
Thank you very much. I will finally be able to try it out!!!
