### ISSUE TITLE
ydotool type Emoji doesn't work

### ISSUE THREAD

**Issue by relma2** [ReimuNotMoe/ydotool#266]
Steps to reproduce:<br />Run `ydotool type 💩` -- it does not type. Does not work with any emoji

This is because in `Client/tool_type.c`, you only support ASCII keyboard inputs and not Unicode. Please support Unicode.

**Comment by ClassicOldSong** [comment]
ydotool type exactly like what you type on a keyboard. You should type out the emoji with ydotool in the same way you type it out yourself.

**Comment by relma2** [comment]
Uh... i think we have a bit of a language barrier.<br />How do I "type it out in the same way i type it out myself"

**Comment by ClassicOldSong** [comment]
It's the literal meaning: ydotool emulates a keyboard, it "types" on that keyboard like you type on a physical keyboard.

**Comment by relma2** [comment]
Ok but how would I type an emoji out on a physical keyboard

**Comment by ClassicOldSong** [comment]
Found this: https://www.omglinux.com/smile-emoji-picker-for-linux/

You need to be creative about how to type it though...

**Comment by relma2** [comment]
Smile copies the Emoji to the clipboard. Each Emoji *does* have a Unicode corresponding key. For example, the 🙂 emoji is Unicode U+1f642. I can type this emoji on a keyboard on *Windows* by holding Alt and typing the code, but I'm not sure how to do it in Linux

**Comment by relma2** [comment]
Wait I figured it out; it's:
1. Hold Ctrl
2. Hold Shift
3. Type 'u'
4. type 1f642 (or the corresponding unicode code)
5. Release Ctrl
6. Release Shift
7. 🙂

**Comment by relma2** [comment]
What would this command be in ydotool?
I don't see a way to hold some keys and not others

**Comment by relma2** [comment]
Closing as you *can* type emoji by holding Ctrl+Space and typing the corresponding Unicode code. These key-presses can be simulated in ydotool
