### ISSUE TITLE
ydotool cannot type Unicode Xray emoji and other Emojis

### ISSUE THREAD

**Issue by relma2** [ReimuNotMoe/ydotool#267]
I am trying to type the xray emoji 🩻 by using the Unicode input. The unicode code is U+1fa7b, so the steps should be
1. Hold Ctrl
2. Hold Shift
3. Press 'u'
4. Press 1fa7b
5. Release Ctrl and Shift
6. 🩻

I am running the equivalent ydotool command `ydotool key 29:1 42:1 22:1 22:0 2:1 2:0 33:1 33:0 30:1 30:0 8:1 8:0 14:1 14:0 42:0 29:0`. But, the output is Ǻ. An A with a circle and accent mark on top.<br />This error also happens for the screwdriver emoji and others. Please fix.

Related to #266

**Comment by relma2** [comment]
I should add that this error does **not** happen for "Smiley" emojis like 🤪 and 🙂

**Comment by ClassicOldSong** [comment]
This is then not an issue with ydotool though, as it only emulates key presses on the keyboard, there's nothing can be fixed here for the specific case.

**Comment by relma2** [comment]
I think it is an issue with ydotool. I tried inputting only the unicode portion of the emoji typer, "u1fa7b", which in ydotool land, is `ydotool key --key-delay 1 22:1 22:0 2:1 2:0 33:1 33:0 30:1 30:0 8:1 8:0 14:1 14:0`. It outputs "u1fa", omitting the 7 and the b entirely. Using the truncated unicode together with Ctrl and Shift yields Ǻ, the "error" character i am seeing.

So `ydotool key` actually **drops** key presses passed in as parameters.

**Comment by ClassicOldSong** [comment]
Add some more delay between keys and try again?

**Comment by relma2** [comment]
I tried key delay 5 and 10; it still outputs a truncated "u1fa"

**Comment by ClassicOldSong** [comment]
Does typing 7 and b separately work?

**Comment by relma2** [comment]
It does not! nothing is outpuutted when I try just 7 and b.

Also, when I put key delay 200, I observed some interesting behavior. The u1fa types normally, then the 7 types, but then the 7 is backspaced, deleting the 7. So entering 'b' actually backspaces.

**Comment by relma2** [comment]
oh wait! the code 14 is actually a backspace! I fetched the backspace code when i meant to fetch the b code, which is 48!

**Comment by relma2** [comment]
I have to call `if keypress in line.split():` instead of `if keypress in line:` because "KEY_B" is a substring of "KEY_BACKSPACE" and the for loop finds the latter line first!

**Comment by relma2** [comment]
Thanks for helping me debug my code. ydotool can type emojis, i just looked up the event code wrong. Closing.
