### ISSUE TITLE
mousemove_relative doesn't work

### ISSUE THREAD

**Issue by icedman** [ReimuNotMoe/ydotool#29]
`ydotool: Unknown tool: mousemove_relative
Run 'ydotool help' if you want a tools list
`

**Comment by icedman** [comment]
I added a pull request to add mousemove_relative tool, along with mousedown, mouseup

**Comment by cprn** [comment]
Was it not merged? I see no open PRs and still get that same error message on Ubuntu 21.04 with `ydotool` installed from repository.

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
