### ISSUE TITLE
Running without sudo

### ISSUE THREAD

**Issue by simao** [ReimuNotMoe/ydotool#32]
Hi,

Is there a way to run ydotool/ydotoold without sudo/root ?

thanks

**Comment by ClassicOldSong** [comment]
Maybe this helps: https://github.com/ReimuNotMoe/ydotool/issues/25#issuecomment-535842993

**Comment by maxice8** [comment]
If you use a system with systemd-logind/elogind you can have this udev rule

```
KERNEL=="uinput", SUBSYSTEM=="misc", TAG+="uaccess", TAG+="udev-acl"
```

**Comment by lnee94** [comment]
or sudo chmod u+s /bin/yodotool /bin/ydotoold

**Comment by ElectricRCAircraftGuy** [comment]
@lnee94 , what does the `u+s` do? I don't understand that one.

**Comment by chconnor** [comment]
> @lnee94 , what does the `u+s` do? I don't understand that one.

from chmod man page: "The letters rwxXst select file mode bits for the affected users: ... set user or group ID  on  execution (s) ..."

The chmod line worked for me, I did not need a udev rule. (Kubuntu 24.10), but the line on kubuntu is:

`sudo chmod u+s /usr/bin/ydotool /usr/bin/ydotool`

**Comment by ElectricRCAircraftGuy** [comment]
> @lnee94 , what does the `u+s` do? I don't understand that one.

I asked the GitHub CoPilot AI in my VSCode editor: 

ElectricRCAircraftGuy:

> What does `u+s` do? `sudo chmod u+s`

GitHub Copilot:

> The `u+s` option in the `chmod` command is used to set the setuid (Set User ID) bit on a file. When the setuid bit is set on an executable file, it allows the file to be executed with the privileges of the file's owner, rather than the privileges of the user who is running the file.
> 
> ...
> 
> Suppose you have an executable file named example owned by the user root. By setting the setuid bit, any user who executes this file will run it with root privileges.
> 
> Verifying the Setuid Bit
> 
> You can verify that the setuid bit has been set by using the `ls -l` command...
