### ISSUE TITLE
ydotool drops custom repeat delay

### ISSUE THREAD

**Issue by hexauniverse** [ReimuNotMoe/ydotool#33]
archlinux, gnome 3.34, runs on xorg

an example:

![](https://i.imgur.com/tRKLj8g.gif)

**Comment by ClassicOldSong** [comment]
Could you provide some more detailed information? In your gif, `ydotool type 1` should type only one `1` to the console, how can you type a bunch of `1`s?

**Comment by hexauniverse** [comment]
@ClassicOldSong, I typed it manually. The gif represents that "delay" setting, which you can see on the left window, changes its value after `ydotool type 1` was executed

**Comment by ClassicOldSong** [comment]
Could you try plug in another keyboard and see if the setting remains?

**Comment by hexauniverse** [comment]
@ClassicOldSong, I've tried this on my laptop and yes, it remains. But I noticed that sometimes all goes normal, and the problem happens only after I run the command several times. Very strange behaviour

**Comment by hexauniverse** [comment]
I've also tried wayland session, it seems there is no problem on it, only xorg

**Comment by ClassicOldSong** [comment]
Probably there's some issue with Xorg on detecting new input devices. Use `ydotoold` and change this setting should have no issue on further usage.

**Comment by hexauniverse** [comment]
Yeah, it helps, thanks a lot. I think the issue can be closed; perhaps this should be described in readme
