### ISSUE TITLE
window id and position and bring to top?

### ISSUE THREAD

**Issue by penguinjeff** [ReimuNotMoe/ydotool#35]
ydotool works great for the implemented features. It seems I need xdotool to get the windows id? and xwininfo to get the window coords

xdotool search --onlyvisible --class google-chrome
(this will return a window id)

use
xwininfo -id <window id>
(this will return the cords of the window)

and I can use xdotool to set a windows on top

Am I suppose to use these 3 programs together to do things?
Or am I doing things wrong?

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/issues/7

**Comment by ClassicOldSong** [comment]
The fundamental difference between `xdotool` and `ydotool` is that `xdotool` uses the internal information provided by `xserver` but `ydotool` doesn't. Since `ydotool` isn't bond to any display server, there's no way for `ydotool` to get such information like window position or mouse position.
