### ISSUE TITLE
ydotoold backend unavailable 

### ISSUE THREAD

**Issue by roipoussiere** [ReimuNotMoe/ydotool#36]
I installed ydotools from sources and experienced this issue:

```
$ pwd # I execute ydotool binary from the build folder, just to be sure
[...]/ydotool/build
$./ydotool type 'Hey guys. This is Austin.'
ydotool: notice: ydotoold backend unavailable (may have latency+delay issues)
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open uinput device
zsh: abort (core dumped)  ./ydotool type 'Hey guys. This is Austin.'
ydotool type 'Hey guys. This is Austin.'
```

Additional information:
```
$ ./ydotool help
<prints the help menu successfully>
$ ls /usr/lib/libuInputPlus.so /usr/lib/libydotool.so /usr/lib/libevdevPlus.so
/usr/lib/libevdevPlus.so  /usr/lib/libuInputPlus.so  /usr/lib/libydotool.so
```

**Comment by roipoussiere** [comment]
Ok, I fixed this by executing ydotool as root. Should it be possible to add a message about this when ydotool fails?

**Comment by hrvoj3e** [comment]
>  fixed this by executing ydotool as root
@roipoussiere  How exactly?

**Comment by zeonin** [comment]
Sounds like a permissions issue on `/dev/uinput`. If your user account doesn't have write privileges, `ydotool`/`ydotoold` won't be able to connect as an input device.

Instead of running as root, a better solution would be to setup a udev rule to allow your user to write to `/dev/uinput` or to use a plain group that has permission.

**Comment by roipoussiere** [comment]
@hrvoj3e result of the `ydotoold` command:

```
ydotoold: listening on socket /tmp/.ydotool_socket
terminate called after throwing an instance of 'std::runtime_error'
  what():  failed to open uinput device
zsh: abort (core dumped)  ydotoold
```
> Instead of running as root, a better solution would be to setup a udev rule to allow your user to write to /dev/uinput or to use a plain group that has permission.

I'm not used to udev rules, how do you do this? I will create a pull-request to add this on the readme. :)

**Comment by hrvoj3e** [comment]
My solution that works.

**Add your user to group input**
```
usermod -aG input <USER>
```
**Add udev rule for `uinput`**
```
echo '## ydotoold fix
##     https://github.com/ReimuNotMoe/ydotool/issues/25#issuecomment-535842993
KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"
' | sudo tee /etc/udev/rules.d/80-uinput.rules > /dev/null
```
**Autostart ydotool**
`/home/<USER>/.config/autostart/ydotoold.desktop`
```
[Desktop Entry]
Type=Application
Terminal=false
Name=ydotool deamon
Exec=/usr/bin/ydotoold
Comment=Generic Linux command-line automation tool (no X!).
Categories=GNOME;GTK;System;
```

**Reboot and test** :smiley:

**Comment by All3xJ** [comment]
> My solution that works.
> 
> **Add your user to group input**
> 
> ```
> usermod -aG input <USER>
> ```
> 
> **Add udev rule for `uinput`**
> 
> ```
> echo '## ydotoold fix
> ##     https://github.com/ReimuNotMoe/ydotool/issues/25#issuecomment-535842993
> KERNEL=="uinput", GROUP="input", MODE="0660", OPTIONS+="static_node=uinput"
> ' | sudo tee /etc/udev/rules.d/80-uinput.rules > /dev/null
> ```
> 
> **Autostart ydotool**
> `/home/<USER>/.config/autostart/ydotoold.desktop`
> 
> ```
> [Desktop Entry]
> Type=Application
> Terminal=false
> Name=ydotool deamon
> Exec=/usr/bin/ydotoold
> Comment=Generic Linux command-line automation tool (no X!).
> Categories=GNOME;GTK;System;
> ```
> 
> **Reboot and test** smiley

this works for me too :)

**Comment by BoostCookie** [comment]
> Add udev rule for `uinput`

I think the udev rule does nothing here.

> **Autostart ydotool**
> `/home/<USER>/.config/autostart/ydotoold.desktop`

I think this is the only reason why this works. The service gets started by the same user that wants to use it.

Maybe it would be smart to give the socket file `/tmp/.ydotool_socket` a group other than the default one of the user that starts it. Then the service could be started by `root`, creating the file with ownership `root:input` with permission `660`, and users which are part of the group `input` could also access the service.

**Comment by JoaoHCopetti** [comment]
Nothing here worked for me.

The only thing that worked was the answer for this question: https://askubuntu.com/questions/1524311/is-there-wtype-like-tool-that-works-with-gnome-on-wayland

Building from source, I tried installing via apt on Debian and didn't had any luck.

Then the process differs a little bit from the oficial docs, you first need to start the `./ydotoold` file then you can use `./ydotool` as normal user, root isn't necessary.
