### ISSUE TITLE
Wrong keyboard mapping

### ISSUE THREAD

**Issue by roipoussiere** [ReimuNotMoe/ydotool#38]
I have a keyboard mapping issue, it's like ydotools types on a keyboard with a wrong keyboard mapping:

```
$ sudo ydotool type 'azerty'
ydotool: notice: ydotoold backend unavailable (may have latency+delay issues)
qwerty%
$ qwerty
```

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/issues/22

**Comment by ReimuNotMoe** [comment]
Couverte dans #22. Je vais m'en occuper aujourd'hui.
