### ISSUE TITLE
[question] What is the records file syntax?

### ISSUE THREAD

**Issue by roipoussiere** [ReimuNotMoe/ydotool#39]
I tried to record some events:

```
sudo ydotool recorder --record foo
sudo ydotool recorder --display foo
```

This outputs some logs similar to this:

```
Offset: 0x2a0
Delay: 0.063964392 second
Event: 4, 4, 458758
-
Offset: 0x2b8
Delay: 0.000004128 second
Event: 1, 46, 1
-
Offset: 0x2d0
Delay: 0.000001284 second
Event: 0, 0, 0
```

What this `Offset` value and these `Event` values and how am I supposed to use them to type ydotools commands?

I tried `sudo ydotool key 0x2d0` but triggers the `0` keyboard key, because `0x2d0` starts with a `0`.

**Comment by ReimuNotMoe** [comment]
Use `ydotool recorder --replay` to replay your record file. 

It's mentioned in `ydotool recorder --help`.

https://github.com/ReimuNotMoe/ydotool/blob/master/Tools/Recorder/Recorder.cpp#L18

**Comment by roipoussiere** [comment]
But I don't want to replay it, I want to understand it.

**Comment by ReimuNotMoe** [comment]
Its structure is defined here: https://github.com/ReimuNotMoe/ydotool/blob/master/Tools/Recorder/Recorder.hpp
