### ISSUE TITLE
Type command does not work with special characters

### ISSUE THREAD

**Issue by Alkindi42** [ReimuNotMoe/ydotool#40]
Hello,

The "type" command does not work with "special characters", example:

> $> ydotool type "Hello world 🤣é²@42"
> ydotool: notice: Using ydotoold backend
> Hello world %                                                                                                                                                                                                   
> 
> $> Hello world

**Comment by ClassicOldSong** [comment]
For `ydotool` actually emulates a user keyboard, since a keyboard can't type in special characters directly, they are also not able to be typed with `ydotool`.
