### ISSUE TITLE
Ship a systemd service file for ydotoold

### ISSUE THREAD

**Issue by ReekyMarko** [ReimuNotMoe/ydotool#42]
Having a systemd service file would allow packagers to install it to the correct place on the users system so they could just do, for example: `systemctl --user enable --now ydotoold` to have it run on startup.

You can have a look at my service file [here](https://github.com/ReekyMarko/dotfiles/blob/master/home/.config/systemd/user/ydotoold.service). The install section would need to be adjusted to use a more generic target to not be Sway specific.

I just wanted to open up this issue before bothering with a PR, to see if you are interested. Let me know what you think.

**Comment by ReimuNotMoe** [comment]
This is a good idea.

However, since I'm not familiar with packaging, I couldn't produce a package that automatically install this file to correct location.

I can just include this file in this repo and let users manually put it to correct place.

**Comment by ReekyMarko** [comment]
@ReimuNotMoe Yes this is totally on the packager to make use of the file, so we don't have to worry about it here.

Do you want me to submit a PR with a file, or can you do it yourself?

I think we could use default.target in the install section, but it would be cool if somebody with a bit more systemd knowledge could chime in.

**Comment by aviau** [comment]
> Do you want me to submit a PR with a file

Please do!

I am currently packaging ydotool for Debian I would prefer do use an upstream-supplied systemd service file.

**Comment by ReekyMarko** [comment]
Alright, I will cook up a PR this evening. I will have to read a bit more about how systemd works to decide on what target I should use.

**Comment by ReekyMarko** [comment]
Sorry, life got in the way so I only now got around to creating the PR. Check #58 for more info.

**Comment by ClassicOldSong** [comment]
Oops thanks for the pr but there's already a merged one on creating a service file: https://github.com/ReimuNotMoe/ydotool/pull/48

**Comment by ReekyMarko** [comment]
Oh right didn't notice it since this was open. Thanks!

**Comment by AutomateAaron** [comment]
@FunctionalHacker I'm trying to get systemd service configured using the provided `.service` and am wondering how you handle the `sudo` permissions required?  Did you create a user for `ytodotool` ~ what persmissions did it need?

**Comment by FunctionalHacker** [comment]
Not sure what distro you are on but at least on Arch Linux, the package ships with a **user** service file. You would just enable and/or start that

```sh
systemctl --user enable ydotool
systemctl --user start ydotool
```

Nothing special is required on my end, it just works. Granted, I don't use ydotool much these days.

**Comment by AutomateAaron** [comment]
I'm running Fedora 43, I put the following into `~/.config/systemd/user/ydotood.service`:
```service
[Unit]
Description=Starts ydotoold Daemon

[Service]
Type=simple
Restart=always
RestartSec=3
ExecStartPre=/bin/sleep 2
ExecStart=ydotoold
ExecReload=/usr/bin/kill -HUP $MAINPID
KillMode=process
TimeoutSec=180

[Install]
WantedBy=basic.target
```
I installed ydotool via `dnf`, the version installed is `ydotool.x86_64 1.0.4-7.fc43 fedora`

When I run `systemctl --user start ydotool`, it enters an exited status, and a `journalctl --user -u  ydotoold` it gives the following logs:
```
Nov 14 11:44:03 fedora systemd[2153]: Starting ydotoold.service - Starts ydotoold Daemon...
Nov 14 11:44:05 fedora systemd[2153]: Started ydotoold.service - Starts ydotoold Daemon.
Nov 14 11:44:05 fedora ydotoold[62526]: failed to open uinput device: Permission denied
Nov 14 11:44:05 fedora ydotoold[62526]: You're advised to run this program as root, or YMMV.
Nov 14 11:44:05 fedora systemd[2153]: ydotoold.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 14 11:44:05 fedora systemd[2153]: ydotoold.service: Failed with result 'exit-code'.
```

I could run it as root, but I'd rather not have to sudo every ydotool command if possible.

**Comment by donhatch** [comment]
@AutomateAaron  I don't have an exact solution yet, but I observe that I can run ydotoold (as root) and ydotool (as user) on the command line successfully as follows, on Ubuntu.  Perhaps this can be used as a building block.

```
sudo ydotoold
  # output: "ydotoold: listening on socket /tmp/.ydotool_socket"
sudo chmod 777 /tmp/.ydotool_socket
ydotool type "This is too damn hard"
```
