### ISSUE TITLE
Please provide a manpage for ydotool and ydotoold

### ISSUE THREAD

**Issue by aviau** [ReimuNotMoe/ydotool#45]
Hello!

It would be great if you provided a manpage so that it can be included in distributions that package ydotool.

( I am a Debian Developper and I am preparing a Debian package)

**Comment by bhepple** [comment]
Where would you have me put it? A new directory 'docs' at the top level?

**Comment by aviau** [comment]
`docs` makes perfect sense!

**Comment by bhepple** [comment]
Maybe don't pull these man pages yet - the cool kids are all using scdoc nowadays and I might take a stab at that.

**Comment by aviau** [comment]
Nah. They were perfectly fine.

**Comment by maxice8** [comment]
This is now present in the `manpage` directory
