### ISSUE TITLE
Plans to implement getactivewindow?

### ISSUE THREAD

**Issue by rbreaves** [ReimuNotMoe/ydotool#56]
I understand with the changes in Wayland it may not be possible, but at the same time it looks like this may just be getting offloaded to the DE and could be obtained via dbus signals with the DE? I am also wondering if the DE's aren't still getting this info from Wayland too though. Either way it'd be a highly useful function to implement.

**Comment by ReimuNotMoe** [comment]
It's not possible. Please read existing issues.
