### ISSUE TITLE
Install libydotool.so and libydotool.a into /usr/local/lib/, not /usr/local/bin/

### ISSUE THREAD

**Issue by bits** [ReimuNotMoe/ydotool#57]
After recent changes to cmake configuration,, `make install` installs `libydotool.so` and `libydotool.a` into `/usr/local/bin` instead of `/usr/local/lib`.

Since ldconfig does not normally look in `/usr/local/bin` for shared objects, libydotool.so cannot be found, so ydotoold does not start:

> `ydotoold: error while loading shared libraries: libydotool.so: cannot open shared object file: No such file or directory`

Until cmake is reconfigured, you could work around this after install by manually moving these two files to a directory that ldconfig searches, and trigger ldconfig to rescan:
```
sudo mv /usr/local/bin/libydotool.{so,a} /usr/local/lib/
sudo ldconfig
```

**Comment by ClassicOldSong** [comment]
Fixed in https://github.com/ReimuNotMoe/ydotool/pull/75
