### ISSUE TITLE
Please version the libydotool.so package

### ISSUE THREAD

**Issue by bhepple** [ReimuNotMoe/ydotool#60]
Please version the libydotool.so package as the fedora packaging guidelines require all shared libraries to be versioned - I am not allowed to package ydotool for fedora with an unversioned shared library. I can versioned it in a patch downstream here in fedora-land but there is a danger that I would choose version numbers that conflict or misalign with a future version number chosen by upstream (yourself).

Much better if you can do the versioning.

Thanks - and thanks again for a great package - I would not be using sway if it were not for ydotool (I would stick to i3wm/xdotool/xvkbd).

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
