### ISSUE TITLE
shared library calls exit

### ISSUE THREAD

**Issue by bhepple** [ReimuNotMoe/ydotool#62]
The fedora auditing tools picked up the fact that the libydotool.so shared library calls `exit` (in several places). A quick google on the topic led me to this explanation:

https://github.com/simbody/simbody/issues/659:

Calling `exit` in a shared libary is generally considered bad practice, as the caller has no way to catch the call, and you will be exiting the main application (the caller). 

I would suggest to replace all `exit` calls by throwing an exception. If the exception is not caught, the behavior will be the same as it is now, but a caller has the option to catch the exception and react appropriately.

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
