### ISSUE TITLE
ydotool key volumeup does not work

### ISSUE THREAD

**Issue by perfect7gentleman** [ReimuNotMoe/ydotool#65]
subj

**Comment by Kommynct** [comment]
Neither volumeup, volumedown, nor XF86AudioLowerVolume or XF86AudioRaiseVolume seem to work.

**Comment by ClassicOldSong** [comment]
Please check https://github.com/YukiWorkshop/libevdevPlus/blob/master/Resource.cpp for available keys.

**Comment by ClassicOldSong** [comment]
These keys should be `KEY_VOLUMEDOWN` and `KEY_VOLUMEUP` according to https://github.com/YukiWorkshop/libevdevPlus/blob/master/Resource.cpp#L71-L72

**Comment by Kommynct** [comment]
ydotool key KEY_VOLUMEUP prints a k

as does volumedown

**Comment by ZaWertun** [comment]
> ydotool key KEY_VOLUMEUP prints a k
> 
> as does volumedown

Use `key_volumeup` or `key_volumedown` instead. Works for me.
Examples:
```shell
ydotool key key_volumeup
```
```shell
ydotool key key_volumedown
```

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
