### ISSUE TITLE
`ydotool <cmd> --help` requires elavated permissions

### ISSUE THREAD

**Issue by ChrisLane** [ReimuNotMoe/ydotool#69]
Currently if I run commands that should just print help messages, ydotool will close with an error.
Examples:
`ydotool click`
`ydotool click --help`

No special permissions should be required to print help text.

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
