### ISSUE TITLE
Repeat command N times

### ISSUE THREAD

**Issue by ChrisLane** [ReimuNotMoe/ydotool#70]
My typical usage for this is repeating a command several times.
To avoid me having to make a while loop whenever I use this command, it would be great if you could add a `--repeat` argument like xdotool has.

Examples usage:
`ydotool type 1 --repeat 10` -> "1111111111"

**Comment by maxice8** [comment]
Can't it be done like a shellscript ?

```sh
for i in $(seq 0 10); do
    ydotool type 1
done
```

**Comment by ChrisLane** [comment]
> To avoid me having to make a while loop whenever I use this command...
Yes but this request is for ease-of-use, to avoid having to wrap ydotool in other things.

**Comment by ChrisLane** [comment]
Looks like this is closed by d6a1e082ce54067581eebb04c256a6de94b59509
