### ISSUE TITLE
Doesn't work on Debian sid anymore

### ISSUE THREAD

**Issue by pshanoop** [ReimuNotMoe/ydotool#77]
Hi, 

Thanks for the great tool, I'm using this with the `pass` to fill passwords. 

Now it seems to be broken on Debian sid, I tried to hunt for the exact issue but couldn't find anything. 
I ran as sudo  both the client and daemon. 
```
sudo ./ydotoold
ydotoold: listening on socket /tmp/.ydotool_socket

sudo ./ydotool type "tests"
ydotool: notice: Using ydotoold backend
```
Even though daemon says `ydotoold: accepted client`  nothing happens.

kernel logs shows new device created as `/devices/virtual/input/input44` 

Socket file permissions
```
srw------- 1 root root 0 Aug  9 21:25 /tmp/.ydotool_socket
```

If you could guide me to debug this issue, it would be very much appreciated.

**Comment by pshanoop** [comment]
`sudo libinput debug-events` also doesn't show any input coming from `ydotool`

**Comment by bits** [comment]
Today's update to [libinput10 1.16.1-1](https://packages.debian.org/sid/libinput10) fixed this for me

**Comment by pshanoop** [comment]
> Today's update to [libinput10 1.16.1-1](https://packages.debian.org/sid/libinput10) fixed this for me

Yes, It seems like this fixed by this update.
