### ISSUE TITLE
What is boost::program_options?

### ISSUE THREAD

**Issue by MichaelAquilina** [ReimuNotMoe/ydotool#8]
Hi there,

I'm trying to compile this project on openSUSE tumbleweed so that I can make it available to download using the opensuse pacakge manager. 

I've successfully compiled libuinputplus and libevdevplus but I cannot figure out what `boost::program_options` actually is. Would you mind elaborating on this so that I can try searching for it in the official opensuse repos?

Would you mind also explaining the difference between libuinputplus/libevdevplus and the standard libraries libuinput and libevdev? (If I can just use the latter it would make the build process a lot simpler)

**Comment by ReimuNotMoe** [comment]
Looks like you need to install [https://software.opensuse.org/package/libboost_program_options1_69_0](https://software.opensuse.org/package/libboost_program_options1_69_0) and its devel packages.

libuInputPlus is a library for playing with Linux's uInput in a easier way.

libevdevPlus is a library for manipulating Linux event devices in a easier way. It can also do string to keycode lookup quickly.
