### ISSUE TITLE
Emulate buttons 4 and 5 of mouse

### ISSUE THREAD

**Issue by gabriel-felipe** [ReimuNotMoe/ydotool#82]
Currently I couldn't emulate buttons 4 and 5 of mouse, those are usually the buttons used for mouse wheel up / down.

Is there any way to achieve that?

**Comment by ReimuNotMoe** [comment]
It's now possible in the newest version. But some code need to be written.

**Comment by gabriel-felipe** [comment]
Thanks, closing this one then, will open it again if I run into some issue.
