### ISSUE TITLE
[Question] How does ydotool figure out the monitor size? Is multimonitor support possible?

### ISSUE THREAD

**Issue by adnion** [ReimuNotMoe/ydotool#83]
I'd like to restrict `ydotool mousemove` to only use a single monitor in a multimonitor setup

**Comment by ReimuNotMoe** [comment]
It's not possible. ydotool has nothing to do with any graphical environment. You have to calculate the sizes & ranges by yourself.

**Comment by adnion** [comment]
Alright, for swaywm the calculation can be based on the name of the active monitor.
`swaymsg -t get_tree | jq '.nodes[] | select(..  | select(.focused?)) | .name' -r`

Getting the pointer position is not supported https://github.com/swaywm/sway/issues/4925

**Comment by Mte90** [comment]
I am trying to move the mouse between my 3 monitors but only on the central one the position is right.

I have a bash like this:
```
if [ "$1" -eq "1" ]; then
    ydotool mousemove -x -1300 -y -150
elif [ "$1" -eq "2" ]; then
    ydotool mousemove -x 300 -y 200
elif [ "$1" -eq "3" ]; then
    ydotool mousemove -x 1600 -y -150
fi
```

absolute also doesn't work in that case as just use the monitor where the cursor is.
