### ISSUE TITLE
Document `/tmp/.ydotool_socket` and make configurable

### ISSUE THREAD

**Issue by akvadrako** [ReimuNotMoe/ydotool#86]
It would be nice if I could run ydotoold with a different socket path. That's because I run most apps in a sandbox with an isolated `/tmp` mount and I would like some to be able to run ydotool. Something under `$XDG_RUNTIME_DIR` would be ideal.

It would also be helpful if the socket path was documented in the README.

**Comment by ReimuNotMoe** [comment]
Now it's possible to change the socket path in `ydotoold`, but I haven't decided how to do that in `ydotool` since it treats command line differently. Do you have any ideas?

**Comment by akvadrako** [comment]
Nice. Why not just a basic `ydotoold --socket /path/to/socket ...` ?

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
