### ISSUE TITLE
make -j `nproc` fails: Final link with libevdevPlus fails

### ISSUE THREAD

**Issue by scott092707** [ReimuNotMoe/ydotool#89]
Linking libevdevPlus fails with two mentions of relocation, one a warning, and finally an error:

[ 88%] Linking CXX shared library libydotool.so
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libevdevPlus.a(Resource.cpp.o): warning: relocation against `_ZNSt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiSt4hashIS5_ESt8equal_toIS5_ESaISt4pairIKS5_iEEED1Ev' in read-only section `.text.startup'
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libevdevPlus.a(evdevPlus.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTISt13runtime_error@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ydotool_library.dir/build.make:268: libydotool.so.0.1.5] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/ydotool_library.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

Ydotool git cloned 12/18 (with the Type.cpp slightly altered to add a pause option)
libuinputplus-dev:
  Installed: 0.1.4-2+b1
libevdevplus-dev:
  Installed: 0.1.1-1+b1
libboost-program-options1.71-dev:
  Installed: 1.71.0-7+b1

from Debian Testing (Bullseye)

Assuming it would actually solve the problem, where would I insert the "-fPIC" compile option?

If one or more files would help, just enumerate them and I will add them.

**Comment by ReimuNotMoe** [comment]
It's no longer a problem. In newest version CMake & CPM will handle all of these and you won't need to compile & install each component by hand.

**Comment by ReimuNotMoe** [comment]
https://github.com/ReimuNotMoe/ydotool/commit/925b2ccc24a6644c2e4be37d9fb64274ee044f76
