### ISSUE TITLE
Type unicode characters

### ISSUE THREAD

**Issue by MeniwaAobaYamaHototogisuHatsuGatsuo** [ReimuNotMoe/ydotool#9]
Good project !!
I tried type unicode characters as below, but they didn't appeared. Ascii char's are well.
Is there any idea?

---- unicode ----
% ydotool type テスト  
ydotool: Executing `type' at 0x7fff66cc3928
argc = 2
argv[1] = テスト

---- ascii ----
% ydotool type test  
ydotool: Executing `type' at 0x7ffd1a5d9f78
argc = 2
argv[1] = test
test

**Comment by ReimuNotMoe** [comment]
It's not possible at this moment since we are emulating a physical keyboard. Unless we find a way to inject into wayland's process.

**Comment by lincot** [comment]
for those who need it, you can emulate Ctrl+V
```sh
cb=$(wl-paste); wl-copy "テスト" && ydotool key 29:1 47:1 47:0 29:0 && wl-copy "$cb"
```
or Ctrl+Shift+V
```sh
cb=$(wl-paste); wl-copy "テスト" && ydotool key 29:1 42:1 47:1 47:0 42:0 29:0 && wl-copy "$cb"
```
