### ISSUE TITLE
Time for a new release? :)

### ISSUE THREAD

**Issue by 1ace** [ReimuNotMoe/ydotool#90]
There's been quite a few changes since the last release (56 commits since `0.1.8`, out of 92 commits total :sweat_smile:)

@ReimuNotMoe do you think you could make another release, so that everyone can benefit from all your work? :wink:

**Comment by ReimuNotMoe** [comment]
> There's been quite a few changes since the last release (56 commits since `0.1.8`, out of 92 commits total sweat_smile)
> 
> @ReimuNotMoe do you think you could make another release, so that everyone can benefit from all your work? wink

I have refactored the entire project and released a new version. You're welcome to test it

**Comment by 1ace** [comment]
> I have refactored the entire project and released a new version.

Awesome, thanks for all the work!

> You're welcome to test it

I've done a summary test of it, and it all seems work :ok_hand:

As a packager I've noticed that `install` doesn't work anymore though, as well as a few other issues.
I'll send a couple of PRs in a bit :)
