### ISSUE TITLE
v0.2.0 :  type skips or mangles first given string

### ISSUE THREAD

**Issue by scott092707** [ReimuNotMoe/ydotool#97]
`scott@ASUS-Prime-B350MA:~$ sudo ydotool > /dev/null 2>&1  type  --next-delay 2000 "abc" "def" "ghi"
defghiscott@ASUS-Prime-B350MA:~$ defghi
bash: defghi: command not found`

`scott@ASUS-Prime-B350MA:~$ sudo ydotool > /dev/null 2>&1  type  "abc" "def" "ghi"
defghiscott@ASUS-Prime-B350MA:~$ defghi
bash: defghi: command not found`

`scott@ASUS-Prime-B350MA:~$ sudo ydotool > /dev/null 2>&1  type --texts "abc" "def" "ghi"
defghiscott@ASUS-Prime-B350MA:~$ defghi
bash: defghi: command not found`

`scott@ASUS-Prime-B350MA:~$ sudo ydotool > /dev/null 2>&1  type --texts "connmanctl" "def" "ghi"
nctldefghiscott@ASUS-Prime-B350MA:~$ nctldefghi
bash: nctldefghi: command not found`

from Debian Testing (Bullseye) in qterminal under Sway 1.5

**Comment by scott092707** [comment]
...I THOUGHT I could get around the problem by simply adding a "" first, but I see now that that does not always work...

`scott@ASUS-Prime-B350MA:~$ sudo ydotool > /dev/null 2>&1  type --texts "" "abc" "def" "ghi"
cdefghiscott@ASUS-Prime-B35cdefghi
bash: cdefghi: command not found`

`scott@ASUS-Prime-B350MA:~$ sudo ydotool > /dev/null 2>&1  type  "" "abc" "def" "ghi"
bcdefghiscott@ASUS-Prime-B350MA:~$ bcdefghi
bash: bcdefghi: command not found`

`scott@ASUS-Prime-B350MA:~$ sudo ydotool > /dev/null 2>&1  type  "" "abc" "def" "ghi"
cdefghiscott@ASUS-Prime-B350MA:~$ cdefghi
bash: cdefghi: command not found`

`scott@ASUS-Prime-B350MA:~$ sudo ydotool > /dev/null 2>&1  type  "" "abc" "def" "ghi"
abcdefghiscott@ASUS-Prime-B350MA:~$ abcdefghi
bash: abcdefghi: command not found`

**Comment by scott092707** [comment]
...I now think that this is probably an example of  "...it will take some time for your graphical environment (X11/Wayland) to recognize and enable the virtual input device. ...", as when I run "sudo ydotoold"  in another terminal tab, the problem seems to go away...

I guess this can be closed.

[Why didn't I use ydotoold from the beginning?
On the version from my pkg mgr (0.1.8-2), ydotoold segfaults upon ydotool being invoked.]

By the way - When I saw an example of ydotoold being used, it was shown/described as being in another terminal [tab].
Could one just 'sudo ydotoold **&**' in the same terminal, or earlier in a script...? (probably also with ' > /dev/null 2>&1 ' )

**Comment by ReimuNotMoe** [comment]
It seems that you're using an older release of ydotool. Please build the latest version and see if the problem persists. Thanks.
