### ISSUE TITLE
type --delay unavailable

### ISSUE THREAD

**Issue by trosh** [ReimuNotMoe/ydotool#98]
The manpage claims that there is a --delay option for the type command, but I get this:
```
% sudo ydotool type --delay=1000 hello
Ooooops! Option ‘delay’ does not exist
type
Usage:
  type [OPTION...] <texts...>

  -h, --help           Show this help
      --key-delay ms   Delay time between keystrokes (default: 12)
      --next-delay ms  Delay time before typing next string on cmdline
                       (default: 50)
      --file path      Specify a file, the contents of which will be be typed
                       as if passed as an argument. The filepath may also be
                       '-' to read from stdin (default: "")
      --texts arg      [Positional] Texts to type
```
I'm using ydotool 0.2.0-1.

**Comment by tardypad** [comment]
I was having the same issue. I see the man page have been fixed in https://github.com/ReimuNotMoe/ydotool/commit/7db62df475338ef0878f7faa584415f2df855384 but it's not release yet.
In the meantime, we have to rely on the --help outputs.

I guess this can be closed then

**Comment by cincodenada** [comment]
On this topic, is it worth supporting `--delay` as an alias for `--next-delay`, to increase compatibility with `xdotool` syntax, or is that a non-goal? I think `--next-delay` is certainly a better name, but might be nice having an alias (even undocumented) to make for an easier transition.

**Comment by raffaem** [comment]
For the `key` option, the man page says that the option is called `--next-delay` in the syntax, then it changes to `--delay`` in the description, and neither of them work:

```
❯ sudo ydotool key --next-delay=1000 a
key: unrecognized option '--next-delay=1000'
❯ sudo ydotool key --delay=1000 a
key: unrecognized option '--delay=1000'
```

**Comment by ReimuNotMoe** [comment]
It seems that you're using an older release of ydotool. Please build the latest version and see if the problem persists. Thanks.
