### ISSUE TITLE
...not sure if this is a bug, or something I'm doing wrong, but ydotool seems to escape from my command line and wreak havok...

### ISSUE THREAD

**Issue by scott092707** [ReimuNotMoe/ydotool#99]
Using ydotool (v0.2.0) from a script that supplies the status_command for sway's swaybar.
I am trying to add network connection display and control (connect/disconnect) from the bar.
I am using connmanctl, and all is good until one needs to connect to a secured network.
For that, connmanctl needs to go into interactive mode (just "connmanctl" - no other arguments).
From its command line, one then needs to issue several commands: "agent on", "connect <service>",
and when it requests a password, supply that.  "quit" to exit the interactive session, and 'exit' to terminate
the terminal (although I used Sakura's '--hold' option so the terminal didn't disappear and I could see what was going on).
This has to be done from a terminal, which I have to launch, with (eventually) the ydotool command.
Here is the command (which is rather complicated, but things don't work if I do it differently - please 
suggest alternatives, if you think of any...):

						  	  sakura  >/home/scott/.config/sway/term-output.txt  2>&1 --hold -e \
						  		"bash -norc -c \
						  		\" sudo ydotool  > /home/scott/.config/sway/ydotool-output.txt  2>&1 \
						  	 	   	type 'connmanctl > /home/scott/.config/sway/connmanctl_output.txt 2>&1 ' , key enter , \
							 	   	type 'agent on'  , key enter , sleep 500 , \
								   	type 'connect ' , type "${cs_service[$i]}" , key enter , sleep 1000 , \
								   	type $password , key enter , sleep 2000 , \
								   	type 'no' , key enter , type 'quit' , key enter , \
								   	type 'exit' , key enter & bash \" " 

(when originally testing, connmanctl's  output redirection was not there, so I could see it, but I now need the output so I can grep it and issue notifications for "Connected" or "Wrong Password").

After finishing, my main Enter key is inoperative (the keypad Enter works, thank goodness...).
If I focus on my file manager (Caja) and a text file is selected, that file is opened, and opened, and opened, ...
It does not stop, and I cannot get the attention of the menu  long enough to quit the text editor.
Other things are equally out of control, but I eventually can get the genie back in the bottle by opening a root terminal with htop, searching for ydotoold, and terminating the process.  Once, I had to do that from another ttty, and sway had eventually crashed, as when I went back to the first one, it had only a grey screen...

I can only speculate that since the last part of the ydotool command line was 'key enter', that it just continued to issue that command over and over.

Is there some sort of parameter that I can add to the line at the end before the '&', to tell ydotool "we're done, shut down now"?

Since before starting the process, I search for the ydotoold process, and start it if I don't find it, perhaps an end parameter could be 'stop both the ydotool command, and the ydotoold process as well' ...

**Comment by ClassicOldSong** [comment]
Unlike xdotool which sends simulated input events to the specific window, ydotool emulates an input device so it types to every program that's on the front.

We have not noticed that repeating command issue, will look into it later.

**Comment by ReimuNotMoe** [comment]
It seems that you're using an older release of ydotool. Please build the latest version and see if the problem persists. Thanks.
